// Real browser, real long PCM recording and WebAudio sources. This is part of the release gate.
import test from 'node:test';import assert from 'node:assert/strict';import {createServer} from 'node:http';import {spawn} from 'node:child_process';import {readFile,mkdtemp,rm} from 'node:fs/promises';import {join,extname} from 'node:path';import {homedir,tmpdir} from 'node:os';
import {CASTLE,SMALL} from '../public/world-definitions.mjs';import {createWorldModel} from '../public/world-model.mjs';import {worldLines} from '../world-service.mjs';import {guardChrome} from '../scripts/headless-guard.mjs';
import {planChapter} from '../../book/plan.mjs';import {templateChapter} from '../../book/template.mjs';import {assemble} from '../../book/assemble.mjs';import {young} from '../../book/tests/fixtures.mjs';import {actorIdsFor} from '../../book/generate.mjs';
const wait=ms=>new Promise(r=>setTimeout(r,ms));
test('all exits silence long voice, music and effects within 150ms; no queued start for 3s; speech steps offer tap', {timeout:240000,skip:!process.env.CHROME},async()=>{
 const image='data:image/svg+xml,'+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="100" height="160"><rect width="100" height="160" fill="gold"/></svg>');
 const layouts=JSON.parse(await readFile(new URL('../book-art-layouts.json',import.meta.url),'utf8'));
 const wav=Buffer.alloc(44+24000*2*12);wav.write('RIFF');wav.writeUInt32LE(wav.length-8,4);wav.write('WAVEfmt ',8);wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(1,22);wav.writeUInt32LE(24000,24);wav.writeUInt32LE(48000,28);wav.writeUInt16LE(2,32);wav.writeUInt16LE(16,34);wav.write('data',36);wav.writeUInt32LE(wav.length-44,40);for(let i=44;i<wav.length;i+=2)wav.writeInt16LE(Math.round(1800*Math.sin((i-44)/2/24000*440*Math.PI*2)),i);
 const lib=JSON.parse(await readFile(new URL('../public/book-art/library.json',import.meta.url),'utf8')),plan=planChapter(young,{date:'2026-03-10',profile:{}});plan.actorIds=actorIdsFor(plan,lib);const chapter=assemble(templateChapter(plan,lib),plan,{library:lib,actors:plan.actorIds.all});
 const attach=v=>{if(!v||typeof v!=='object')return;if(v.text&&v.voice)v.clip='0000000000000000.wav';for(const x of Object.values(v))attach(x);};const magicPage=chapter.pages.find(p=>p.kind==='story'&&!p.action&&!p.choice);assert.ok(magicPage);delete magicPage.action;magicPage.magic={word:'cat',object:'Magic word',read:{text:'Cat.',voice:'af_bella',speed:.8},after:[]};attach(chapter);delete chapter.ui.traceIt;const quietPage={...structuredClone(magicPage),magic:undefined,action:undefined,choice:undefined,say:[{text:'Here is our quiet garden.',voice:'af_bella',speed:.8,clip:'0000000000000000.wav'}]};chapter.pages.push(quietPage);
 let definition=CASTLE,model=createWorldModel(definition),state=model.freshWorld(),holdHome=false;const lines=()=>Object.fromEntries(Object.entries(worldLines({},definition)).map(([k,v])=>[k,{...v,clip:'0000000000000000.wav'}]));
 const art=()=>({backgrounds:Object.fromEntries(Object.entries(definition.ROOMS).map(([id,r])=>[r.bg||id,{url:image,size:[1366,768],fit:'contain',groundStart:.5,keepOut:[]}])),actors:Object.fromEntries(['hero',...new Set(Object.values(definition.ROOMS).map(r=>r.friend))].map(id=>[id,{name:id,h:.4,poses:{idle:{url:image,ar:.45}}}])),props:{chest:{url:image}}});
 const server=createServer(async(req,res)=>{try{const u=new URL(req.url,'http://x');if(u.pathname==='/'&&holdHome)await wait(4200);res.setHeader('Cache-Control','no-store');const json=j=>{res.setHeader('Content-Type','application/json');res.end(JSON.stringify(j));};
 if(u.pathname.startsWith('/book-voice/')){res.setHeader('Content-Type','audio/wav');res.end(wav);return;}
 if(u.pathname==='/api/world'){if(req.method==='POST'){let raw='';for await(const c of req)raw+=c;const out=model.worldAction(state,JSON.parse(raw));state=out.state;json(out);}else json({definition,state,art:art(),lines:lines(),name:'Hero'});return;}
 if(u.pathname==='/api/book/review/gate')return json({unlocked:true});
 if(u.pathname==='/api/book'&&u.searchParams.has('peek'))return json({open:false});
 if(u.pathname==='/__deploy/version')return json({hub:''});
 if(u.pathname==='/api/book')return json({chapter,date:chapter.date,progress:{page:0},collection:{keys:[],words:[]},open:true});
 if(u.pathname==='/api/config')return json({players:[{id:'hero',name:'Hero',homeShortcuts:[]}],games:{},menuTimeZone:'UTC'});
 if(u.pathname.startsWith('/api/'))return json({ok:true,available:true,order:[],games:[]});
 if(u.pathname.startsWith('/g/')){res.setHeader('Content-Type','text/html');return res.end(`<html><head><script src="/audio-scope.mjs"></script></head><body><button>Play</button><script>addEventListener('message',e=>{if(e.data?.type==='family-status')setTimeout(()=>parent.postMessage({type:'family-status',pending:0,dirty:false},location.origin),350);});</script></body></html>`);}
 if(u.pathname==='/book-harness'){res.setHeader('Content-Type','text/html');return res.end(`<html><head><link rel="stylesheet" href="/book.css"></head><body><main id="main"></main><script type="module">import {mountBook} from '/book.mjs';globalThis.__dispose=mountBook(document.querySelector('main'),{player:'hero',book:await fetch('/api/book').then(r=>r.json()),preview:true,onDone:()=>location.href='/'});</script></body></html>`);}
 if(u.pathname==='/dribble.mjs'){res.setHeader('Content-Type','text/javascript');res.end(await readFile(new URL('../dribble.mjs',import.meta.url)));return;}
 let path=u.pathname==='/'?'index.html':u.pathname==='/world'?'world.html':u.pathname.slice(1);if(path.includes('..'))throw Error('path');res.setHeader('Content-Type',({'.mjs':'text/javascript','.css':'text/css','.html':'text/html','.svg':'image/svg+xml','.png':'image/png','.webp':'image/webp'})[extname(path)]||'application/octet-stream');res.end(await readFile(new URL('../public/'+path,import.meta.url)));}catch(e){if(process.env.AUDIO_DEBUG)console.log('missing',req.url,e.message);res.writeHead(404);res.end();}});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port,profile=await mkdtemp(join(tmpdir(),'audio-exits-'));let chrome,ws;
 try{chrome=guardChrome(spawn(process.env.CHROME||join(homedir(),'.local/share/family-games/bin/test-chrome'),['--headless=new','--remote-debugging-port=0','--user-data-dir='+profile,'--no-first-run','--mute-audio','--autoplay-policy=no-user-gesture-required','about:blank'],{stdio:'ignore'}));let port;for(let i=0;i<100;i++){try{port=(await readFile(join(profile,'DevToolsActivePort'),'utf8')).split('\n')[0];break;}catch{await wait(50);}}assert.ok(port);
 // The debugger can accept requests before the initial page target exists.
 let target;for(let i=0;i<100;i++){target=(await fetch('http://127.0.0.1:'+port+'/json').then(r=>r.json())).find(t=>t.type==='page');if(target)break;await wait(50);}assert.ok(target,'Chrome page target became ready');ws=new WebSocket(target.webSocketDebuggerUrl);await new Promise(r=>ws.onopen=r);let seq=0;const pending=new Map();ws.onmessage=e=>{const v=JSON.parse(e.data);if(process.env.AUDIO_DEBUG&&v.method==='Runtime.exceptionThrown')console.log(v.params.exceptionDetails);if(v.id){pending.get(v.id)?.(v);pending.delete(v.id);}};
 const send=(method,params={})=>new Promise((ok,no)=>{const id=++seq,t=setTimeout(()=>no(Error(method)),10000);pending.set(id,v=>{clearTimeout(t);v.error?no(Error(JSON.stringify(v.error))):ok(v.result);});ws.send(JSON.stringify({id,method,params}));});
 const js=async expression=>{const r=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result?.value;};
 const until=async expression=>{for(let i=0;i<400;i++){if(await js(expression))return;await wait(30);}throw Error('Not ready: '+expression+' '+await js('document.body.innerText'));};
 await send('Page.enable');await send('Runtime.enable');await send('Emulation.setDeviceMetricsOverride',{width:1366,height:768,deviceScaleFactor:1,mobile:false});await send('Page.addScriptToEvaluateOnNewDocument',{source:`globalThis.__media=new Set();globalThis.__sources=new Set();globalThis.__starts=[];const play=HTMLMediaElement.prototype.play;HTMLMediaElement.prototype.play=function(){__media.add(this);this.addEventListener('playing',()=>__starts.push(performance.now()));return play.call(this);};for(const name of ['AudioBufferSourceNode','OscillatorNode']){const P=globalThis[name].prototype,start=P.start,stop=P.stop;P.start=function(...a){__sources.add(this);this.addEventListener('ended',()=>__sources.delete(this),{once:true});__starts.push(performance.now());return start.apply(this,a);};P.stop=function(...a){__sources.delete(this);return stop.apply(this,a);};}`});
 const open=async path=>{await send('Page.navigate',{url:base+path});await until(`!!globalThis.familyAudio`);};
 const prime=async()=>{await js(`(async()=>{document.body.click();globalThis.__long=new Audio('/book-voice/0000000000000000.wav');await __long.play();globalThis.__ctx=new AudioContext();await __ctx.resume();globalThis.__osc=__ctx.createOscillator();__osc.connect(__ctx.destination);__osc.start();const buffer=__ctx.createBuffer(1,24000*12,24000);globalThis.__music=__ctx.createBufferSource();__music.buffer=buffer;__music.loop=true;__music.connect(__ctx.destination);__music.start();})()`);assert.ok(await js(`[...__media].some(a=>!a.paused)&&__sources.size>=2`));};
 const silence=async(action,label)=>{await prime();const r=await js(`(async()=>{const at=performance.now();${action};await new Promise(r=>setTimeout(r,140));const playing=[...__media].filter(a=>!a.paused&&!a.ended).length+__sources.size;const boundary=performance.now();await new Promise(r=>setTimeout(r,3100));return {playing,later:__starts.filter(t=>t>boundary).length,ms:boundary-at};})()`);assert.equal(r.playing,0,label+' still playing after 140ms');assert.equal(r.later,0,label+' queued audio started');};
 for(const d of (process.env.AUDIO_DEBUG?[]:[CASTLE,SMALL])){definition=d;model=createWorldModel(d);state={...model.freshWorld(),questStarted:true,tutorial:{walk:true,talk:true}};
 await open('/world?player=hero&preview=1');await until(`document.querySelector('#world')?.hidden===false`);await silence(`document.querySelector('#map-button').click()` ,d.id+' Map');await silence(`document.querySelector('#map .continue').click()`,d.id+' Map close');
 // Open a real puzzle by tap and walk, then close it while audio is still long.
 state={...state,room:d.early?'brain-world':'chess-courtyard'};await open('/world?player=hero&preview=1');await until(`!!document.querySelector('[data-object^="gate-"]')`);await js(`document.querySelector('[data-object^="gate-"]').click()`);await until(`document.querySelector('#challenge').hidden===false`);await silence(`document.querySelector('#challenge .close').click()`,d.id+' puzzle close');
 await silence(`document.querySelector('.signpost').click()`,d.id+' room exit');
 if(!d.early){state={...state,room:'castle-forest'};await open('/world?player=hero&preview=1');await until(`!!document.querySelector('.opening')`);await silence(`document.querySelector('.opening').click()`,'castle opening');}
 await silence(`Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'))`,d.id+' hidden');
 await open('/world?player=hero&preview=1');await until(`document.querySelector('#world')?.hidden===false`);await silence(`dispatchEvent(new PopStateEvent('popstate'))`,d.id+' browser Back');await silence(`dispatchEvent(new PageTransitionEvent('pagehide'))`,d.id+' pagehide');
 // Keep the old document inspectable while the destination response is delayed.
 // Home must silence its sources before navigation can finish.
 await open('/world?player=hero&preview=1');await until(`document.querySelector('#world')?.hidden===false`);holdHome=true;await silence(`document.querySelector('#home-button').click()`,d.id+' Home');holdHome=false;await until(`!!document.querySelector('#grown-ups')`);
 }
 await open('/?player=hero');await until(`!!document.querySelector('#grown-ups')`);await silence(`document.querySelector('#home').click()`,'hub Home');await silence(`location.hash='more'`,'hub Back/hash');await silence(`Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'))`,'hub hidden');
 await open('/?player=hero#letter-quest');await until(`!!document.querySelector('iframe')?.contentWindow?.familyAudio`);await js(`(async()=>{const f=document.querySelector('iframe').contentWindow;await f.eval("(async()=>{document.body.click();globalThis.longClip=new Audio('/book-voice/0000000000000000.wav');await longClip.play();globalThis.fxContext=new AudioContext();await fxContext.resume();const effect=fxContext.createOscillator();effect.connect(fxContext.destination);effect.start();})()");globalThis.oldMedia=f.__media;globalThis.oldSources=f.__sources;globalThis.oldStarts=f.__starts;globalThis.oldBoundary=f.performance.now();document.querySelector('#home').click();})()`);await wait(140);assert.equal(await js(`[...oldMedia].filter(a=>!a.paused&&!a.ended).length+oldSources.size`),0,'Embedded game stayed audible while confirming its save');await wait(3100);assert.equal(await js(`oldStarts.filter(t=>t>oldBoundary+140).length`),0,'Detached game queued audio');
 await open('/book-harness');await until(`!!document.querySelector('.bk-open')`);await silence(`document.querySelector('.bk-exit').click()`,'Book Back');
 await open('/book-harness');await until(`!!globalThis.__bookGo`);await silence(`__bookGo(${chapter.pages.length-1})`,'Book page');assert.equal(await js(`!!document.querySelector('.bk-quest')`),false,'A silenced page advanced without narration or a tap');await silence(`Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'))`,'Book hidden');
 // Each authored speech step has its same answer available by tap immediately, even with recognition available.
 const countPage=chapter.pages.findIndex(p=>p.beat?.kind==='count');if(countPage>=0){chapter.calm={pages:{[countPage]:{done:{text:'Tap done when you are ready.',voice:'af_bella',speed:.8,clip:'0000000000000000.wav'}}}};await open('/book-harness');await until(`!!globalThis.__bookGo`);await js(`__bookGo(${countPage})`);await until(`!!document.querySelector('.bk-thing')`);await js(`document.querySelector('.bk-thing').click()`);await until(`document.querySelector('.bk-calm-done')?.hidden===false`);assert.equal(await js(`document.querySelector('.bk-calm-done').disabled`),false);}
 const speechPages=chapter.pages.map((p,i)=>p.magic||p.beat?.kind==='teach-letter'?i:null).filter(i=>i!==null);assert.ok(speechPages.length);
 assert.ok(chapter.pages.some(p=>p.magic)&&chapter.pages.some(p=>p.beat?.kind==='teach-letter'));
 for(const page of speechPages){if(process.env.AUDIO_DEBUG)console.log('speech page',page,chapter.pages[page].kind,chapter.pages[page].beat?.kind);await open('/book-harness');await until(`!!globalThis.__bookGo`);await js(`__bookGo(${page})`);await until(`!!document.querySelector('[data-speech-tap]')`);assert.equal(await js(`document.querySelector('[data-speech-tap]').disabled`),false);await js(`document.querySelector('[data-speech-tap]').click()`);}
 await open('/book-harness');await until(`!!globalThis.__bookGo`);await js(`__bookGo(${chapter.pages.indexOf(magicPage)})`);await until(`!!document.querySelector('.bk-magic')`);const timing=await js(`(async()=>{const at=performance.now();const feedback=new Promise(resolve=>{const observer=new MutationObserver(()=>{observer.disconnect();resolve(performance.now()-at);});observer.observe(document.querySelector('main'),{attributes:true,childList:true,subtree:true});setTimeout(()=>{observer.disconnect();resolve(null);},500);});document.querySelector('.bk-hear').click();const visible=await feedback;for(let i=0;i<100;i++){const start=__starts.find(t=>t>at);if(start)return {visible,voice:start-at};await new Promise(r=>setTimeout(r,10));}return {visible,voice:null};})()`);assert.ok(timing.visible!==null&&timing.visible<=100,JSON.stringify(timing));assert.ok(timing.voice!==null&&timing.voice<=300,JSON.stringify(timing));console.log('Book replay timing',JSON.stringify(timing));
 }finally{ws?.close();if(chrome&&chrome.exitCode===null&&chrome.signalCode===null){const done=new Promise(r=>chrome.once('exit',r));chrome.kill();await done;}server.closeAllConnections();await new Promise(r=>server.close(r));await rm(profile,{recursive:true,force:true,maxRetries:5,retryDelay:100});}
});
