import test from 'node:test';import assert from 'node:assert/strict';
import {fresh,act,openRoutes,DIRS,RULES} from '../dribble.mjs';
const go=(p,a)=>act(p,{rulesVersion:RULES,revision:p.revision,roundId:p.round?.id,...a});
function opening(p){for(let i=0;!openRoutes(p.round).length&&i<8;i++)go(p,{type:'feint',move:p.round.lastFake==='left'?'right':'left'});assert(openRoutes(p.round).length);}
function finish(p){go(p,{type:'start'});for(let i=0;!p.round.done&&i<3;i++){opening(p);go(p,{type:'move',move:openRoutes(p.round)[0]});}assert(p.round.done);}
test('All 800 duels require creating an opening and remain solvable, including touchlines and recoveries',()=>{for(let level=1;level<=8;level++)for(let serial=0;serial<100;serial++){const p=fresh('admin',level);p.serial=serial;go(p,{type:'start'});assert.deepEqual(openRoutes(p.round),[]);finish(p);assert.equal(p.dribbles,1);assert.equal(p.goals,0);assert.equal(p.history[0].helped,false);}});
test('Charging a balanced defender or closed feet fails; a step does not guarantee a nutmeg',()=>{const p=fresh('admin');go(p,{type:'start'});for(const move of DIRS)assert.equal(go(p,{type:'move',move}).kind,'blocked');go(p,{type:'feint',move:'left'});assert.equal(p.round.gap,false);assert.deepEqual(openRoutes(p.round),['right']);assert.equal(go(p,{type:'move',move:'middle'}).kind,'blocked');assert.equal(go(p,{type:'move',move:'right'}).kind,'escaped');assert(p.history[0].helped);});
test('A patient defender will not follow repeated identical fakes; a changed fake creates the opening',()=>{const p=fresh('admin',3);go(p,{type:'start'});for(let i=0;i<12;i++){go(p,{type:'feint',move:'left'});assert(p.round.balanced);}go(p,{type:'feint',move:'right'});assert(!p.round.balanced);assert(openRoutes(p.round).includes('left'));});
test('Three independent duels advance; help/corrected answers do not; manual settings cancel immediately',()=>{const p=fresh('admin');for(let i=0;i<3;i++)finish(p);assert.equal(p.level,2);go(p,{type:'start'});const old=p.round.id;go(p,{type:'level',level:8});assert.notEqual(p.round.id,old);assert.equal(p.dribbles,3);assert.equal(p.round.steps,3);assert.throws(()=>go(p,{type:'move',move:'left',roundId:old}),/changed/);assert.throws(()=>go(p,{type:'level',level:9}),/1 to 8/);const q=fresh('admin');for(let i=0;i<5;i++){go(q,{type:'start'});const hint=go(q,{type:'hint'});assert.deepEqual(hint.routes,[]);finish(q);}assert.equal(q.level,1);});
test('Legacy results are retained separately, stale clients rejected, new count starts at zero',()=>{const p=fresh('admin');delete p.rulesVersion;delete p.dribbles;p.goals=19;p.round={id:'old',done:false};assert.throws(()=>act(p,{revision:0,type:'start'}),/Refresh/);assert.equal(p.goals,19);go(p,{type:'start'});assert.equal(p.goals,19);assert.equal(p.dribbles,0);assert.equal(p.history[0].round.id,'old');finish(p);assert.equal(p.dribbles,1);assert.equal(p.goals,19);});
