import test from 'node:test';import assert from 'node:assert/strict';import http from 'node:http';
import {rewriteText,proxy} from '../proxy.mjs';
test('Root assets, imports, APIs, CSS and voice URLs stay scoped without corrupting router separators',()=>{const p='/g/word-arcade/admin/';assert.equal(rewriteText('fetch(`/api/${id}`); import "/assets/x.js"; const slash="/"; const https="https://example.com/a";',p),'fetch(`/g/word-arcade/admin/api/${id}`); import "/g/word-arcade/admin/assets/x.js"; const slash="/"; const https="https://example.com/a";');assert.equal(rewriteText('url(/icons/a.png)',p),'url(/g/word-arcade/admin/icons/a.png)');});
test('Concatenated action/event suffixes are not mistaken for root paths',()=>{assert.equal(rewriteText('`/api/${id}` + "/events"','/g/game/admin/'),'`/g/game/admin/api/${id}` + "/events"');});
test('Proxy rewrites app traffic, strips credentials, preserves body and constrains player',async()=>{
 let received;const up=http.createServer(async(req,res)=>{let body='';for await(const b of req)body+=b;received={headers:req.headers,url:req.url,body};res.setHeader('X-Frame-Options','DENY');res.setHeader('Content-Security-Policy',"default-src 'self'; frame-ancestors 'none'");res.setHeader('Content-Type','text/html');res.end('<html><head><script src="/app.mjs"></script></head></html>');});await new Promise(r=>up.listen(0,'127.0.0.1',r));
 const hub=http.createServer((req,res)=>proxy(req,res,{port:up.address().port,prefix:'/g/game/admin/',path:req.url,player:'admin',players:['admin','beginner'],game:'game'},()=>{}));await new Promise(r=>hub.listen(0,'127.0.0.1',r));
 try{const base='http://127.0.0.1:'+hub.address().port;const r=await fetch(base+'/?player=beginner',{method:'POST',headers:{Origin:'http://localhost:9999',Cookie:'private=1',Authorization:'secret'},body:'keep-this'});const html=await r.text();assert(html.includes('src="/g/game/admin/app.mjs"'));assert(html.includes('src="/bridge.mjs"'));assert.equal(r.headers.get('x-frame-options'),'SAMEORIGIN');assert(r.headers.get('content-security-policy').includes("frame-ancestors 'self'"));assert.equal(received.url,'/?player=admin');assert.equal(received.body,'keep-this');assert.equal(received.headers.cookie,undefined);assert.equal(received.headers.authorization,undefined);assert.equal((await fetch(base+'/api/beginner')).status,409);}finally{hub.closeAllConnections();up.closeAllConnections();await Promise.all([new Promise(r=>hub.close(r)),new Promise(r=>up.close(r))]);}
});
