import test from 'node:test';import assert from 'node:assert/strict';
import {newProfile,startMaze,action,gridSize,MAX_LEVEL} from '../engine.mjs';
test('Book-scale starting mazes have genuinely branching routes, not relabeled beginner boards',()=>{for(let seed=1;seed<=20;seed++)for(const player of ['beginner','explorer']){const m=startMaze(newProfile(player),seed);assert.equal(m.n,player==='explorer'?31:19);assert.ok(m.metrics.deadEnds>=(player==='explorer'?100:35));assert.ok(m.metrics.decisions>=(player==='explorer'?25:12));assert.ok(m.metrics.steps>=(player==='explorer'?140:70));}assert.equal(gridSize(MAX_LEVEL),61);});
test('Recalibration archives the complete previous maze, preserving awards/history and is one-time',()=>{const p=newProfile('explorer');delete p.calibration;p.level=4;p.active={id:'old',n:7,trail:[1,2],finished:false};p.completed=3;p.stars=9;p.history=[{type:'fixture'}];action(p,{type:'recalibrate',seed:4});assert.equal(p.level,12);assert.equal(p.active.n,31);assert.deepEqual(p.archivedMazes[0].trail,[1,2]);assert.equal(p.completed,3);assert.equal(p.stars,9);assert.equal(p.history.length,1);const id=p.active.id;action(p,{type:'recalibrate',seed:22});assert.equal(p.active.id,id);assert.equal(p.archivedMazes.length,1);});
test('Harder/smaller requests move one level without awarding completions',()=>{const p=newProfile('beginner');action(p,{type:'start',seed:1});action(p,{type:'challenge',delta:1,seed:2});assert.equal(p.active.n,21);assert.equal(p.completed,0);assert.equal(p.history.at(-1).type,'requested-harder');action(p,{type:'challenge',delta:-1,seed:3});assert.equal(p.active.n,19);assert.equal(p.stars,0);});
test('Level 9 can return to 8, including buttons in older already-open clients',()=>{for(const delta of [1,2]){const p=newProfile('explorer');p.level=9;action(p,{type:'start',seed:1});action(p,{type:'challenge',delta:-delta,seed:2});assert.equal(p.level,8);assert.equal(p.active.n,23);action(p,{type:'challenge',delta,seed:3});assert.equal(p.level,9);assert.equal(p.completed,0);}});
test('Reading mistakes do not lower maze-solving progression',()=>{const p=newProfile('explorer');action(p,{type:'start',seed:3});p.active.wrong=20;action(p,{type:'moves',maze:p.active.id,cells:p.active.solution.slice(1)});assert.equal(p.level,14);});
test('A burst of Harder taps is one history row and never pushes finished mazes out',()=>{const p=newProfile('beginner');action(p,{type:'start',seed:1});action(p,{type:'moves',maze:p.active.id,cells:p.active.solution.slice(1)});assert.equal(p.completed,1);const done=p.history.at(-1);for(let i=0;i<60;i++)action(p,{type:'challenge',delta:1,seed:10+i});assert.equal(p.level,MAX_LEVEL);const rows=p.history.filter(h=>h.type==='requested-harder');assert.equal(rows.length,1);assert.equal(rows[0].taps,60);assert.equal(rows[0].to,MAX_LEVEL);action(p,{type:'challenge',delta:-1,seed:99});assert.equal(p.history.at(-1).type,'requested-easier');assert.equal(p.level,MAX_LEVEL-1);p.history.at(-1).at=new Date(Date.now()-120000).toISOString();action(p,{type:'challenge',delta:-1,seed:100});assert.equal(p.history.filter(h=>h.type==='requested-easier').length,2);assert.deepEqual(p.history.find(h=>!h.type),done);});
test('History trimming drops request rows before finished mazes',async()=>{const {trimHistory}=await import('../engine.mjs');const rows=[{id:'a'},...Array.from({length:498},(_,i)=>({type:'requested-easier',i})),{id:'b'},{id:'c'}];const out=trimHistory(rows);assert.equal(out.length,500);assert.deepEqual(out.filter(h=>!h.type).map(h=>h.id),['a','b','c']);const only=Array.from({length:505},(_,i)=>({id:i}));assert.equal(trimHistory(only).length,500);assert.equal(trimHistory(only)[0].id,5);});
