import test from 'node:test';import assert from 'node:assert/strict';
import {makeMaze,route,newProfile,startMaze,action,traceSegment,pendingPuzzle} from '../engine.mjs';
test('All shapes, seeds and difficulties are connected trees with reachable ends',()=>{for(let level=1;level<=27;level++)for(let seed=1;seed<=8;seed++){const m=makeMaze(level,seed),active=m.cells.flatMap((v,i)=>v===null?[]:[i]);let edges=0;for(const id of active){for(const next of m.cells[id]){assert.ok(m.cells[next].includes(id));assert.equal(Math.abs(id%m.n-next%m.n)+Math.abs(Math.floor(id/m.n)-Math.floor(next/m.n)),1);edges++;}}const seen=new Set([m.start]),q=[m.start];for(let k=0;k<q.length;k++)for(const v of m.cells[q[k]])if(!seen.has(v)){seen.add(v);q.push(v);}assert.equal(seen.size,active.length);assert.equal(edges/2,active.length-1);assert.equal(m.solution.at(-1),m.goal);assert.ok(m.solution.length>5);}});
test('Children start separately, Explorer with a larger maze',()=>{const f=newProfile('explorer'),d=newProfile('beginner');assert.ok(startMaze(f,40).n>startMaze(d,40).n);assert.equal(f.completed,0);assert.equal(d.level,6);});
function solve(p){const a=p.active;for(const cell of a.solution.slice(1)){action(p,{type:'moves',maze:a.id,cells:[cell]});const c=pendingPuzzle(a);if(c)action(p,{type:'answer',answer:c.puzzle.answer});}}
test('Clean completions advance difficulty; assisted practice keeps its level and full completion reward',()=>{let p=newProfile('explorer');for(let i=0;i<2;i++){action(p,{type:'start',seed:i+1});solve(p);}assert.equal(p.level,16);assert.equal(p.completed,2);assert.equal(p.stars,6);for(let i=0;i<2;i++){action(p,{type:'start',seed:i+40});action(p,{type:'hint'});action(p,{type:'hint'});solve(p);}assert.equal(p.level,16);assert.equal(p.completed,4);assert.equal(p.stars,12);});
test('Puzzle gates cannot be skipped and answers do not auto-solve mazes',()=>{for(const player of ['beginner','explorer']){const p=newProfile(player);action(p,{type:'mode',mode:'puzzles'});action(p,{type:'start',seed:75});const a=p.active,c=a.checkpoints[0],k=a.solution.indexOf(c.cell);action(p,{type:'moves',maze:a.id,cells:a.solution.slice(1,k+1)});assert.throws(()=>action(p,{type:'moves',maze:a.id,cells:[a.solution[k+1]]}));action(p,{type:'answer',answer:'wrong'});assert.equal(a.wrong,1);assert.equal(c.solved,false);action(p,{type:'answer',answer:c.puzzle.answer});assert.equal(c.solved,true);assert.equal(p.completed,0);}});
test('High-speed tracing follows corridors; cannot pass walls or wrap around',()=>{for(let seed=1;seed<30;seed++){const p=newProfile('beginner'),a=startMaze(p,seed),c=id=>({x:id%a.n+.5,y:Math.floor(id/a.n)+.5});for(const id of a.solution.slice(1)){const before=a.trail.at(-1),out=traceSegment(a,c(before),c(id));assert.deepEqual(out,[id]);}assert.equal(a.trail.at(-1),a.goal);const b=startMaze(p,seed);traceSegment(b,c(b.start),{x:-20,y:20});for(let i=1;i<b.trail.length;i++)assert.ok(b.cells[b.trail[i-1]].includes(b.trail[i]));}});
test('Progress persists through JSON, completion cannot count twice, old maze IDs fail',()=>{let p=newProfile('beginner');action(p,{type:'start',seed:1});action(p,{type:'moves',maze:p.active.id,cells:[p.active.solution[1]]});p=JSON.parse(JSON.stringify(p));const rest=p.active.solution.slice(2);action(p,{type:'moves',maze:p.active.id,cells:rest});assert.equal(p.completed,1);action(p,{type:'moves',maze:p.active.id,cells:[]});assert.equal(p.completed,1);assert.throws(()=>action(p,{type:'moves',maze:'old',cells:[0]}));});
