import test from 'node:test';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';import {mkdtempSync,readFileSync,readdirSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
test('HTTP saves, revision conflicts, isolation and local-origin guard',async()=>{const data=mkdtempSync(join(tmpdir(),'maze-garden-test-'));const child=spawn(process.execPath,['server.mjs'],{cwd:new URL('..',import.meta.url),env:{...process.env,PORT:'0',HOST:'127.0.0.1',MAZE_DATA_DIR:data}});let base;try{base=await new Promise((resolve,reject)=>{child.stdout.once('data',d=>resolve(String(d).trim().split(' ').at(-1)));child.once('error',reject);child.once('exit',code=>reject(Error('Server exited '+code)));});
 const get=async p=>(await fetch(base+'/api/state?player='+p)).json();const post=async(p,input,headers={})=>fetch(base+'/api/action?player='+p,{method:'POST',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify(input)});
 let f=await get('explorer'),d=await get('beginner');assert.equal(f.level,12);assert.equal(d.level,6);let r=await post('explorer',{type:'start',revision:0});assert.equal(r.status,200);f=await r.json();const first=f.active.solution[1];r=await post('explorer',{type:'moves',revision:f.revision,maze:f.active.id,cells:[first]});assert.equal(r.status,200);f=await r.json();assert.deepEqual((await get('explorer')).active.trail,[f.active.start,first]);assert.equal((await get('beginner')).active,null);
 r=await post('explorer',{type:'hint',revision:0});assert.equal(r.status,409);r=await post('explorer',{type:'hint',revision:f.revision},{Origin:'https://evil.example'});assert.equal(r.status,403);
 r=await post('explorer',{type:'moves',revision:f.revision,maze:f.active.id,cells:[999]});assert.equal(r.status,400);assert.equal((await get('explorer')).revision,f.revision);assert.deepEqual(JSON.parse(readFileSync(join(data,'explorer.json'))).active.trail,f.active.trail);
 for(const name of ['/','/app.mjs','/hint-view.mjs','/style.css','/engine.mjs','/icon.svg','/icon-192.png','/icon-512.png','/manifest.webmanifest']){const response=await fetch(base+name);assert.equal(response.status,200,name);assert.equal(response.headers.get('cache-control'),'no-store');}
 assert.equal((await fetch(base+'/api/state?player=__proto__')).status,400);assert.equal((await fetch(base+'/%2e%2e%2fserver.mjs')).status,403);assert.ok(readdirSync(join(data,'logs')).length);
 }finally{child.kill('SIGTERM');} });
