'use client';
import {useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import {PICTURE_LABELS,DOODLE_ICONS} from '@/lib/doodle.mjs';
import {MISSIONS,PARTS,fitInk} from '@/lib/art.mjs';
import {UPPER,LOWER,DIGITS,guessLine,labelLine,labelName,validArtLabel} from '@/lib/symbol-recognition.mjs';
import {useInkTools} from './ink-tools';
type Point=[number,number];
type Props={art:any,act:(input:any)=>Promise<any>,busy:boolean,onSpeak:(text:string)=>void};
export function GuessDrawing({ink,art,act,busy,onSpeak}:Props&{ink:Point[][]}){
 const [message,setMessage]=useState(''),[choose,setChoose]=useState(false),[mode,setMode]=useState('auto'),[labels,setLabels]=useState('pictures'),[number,setNumber]=useState('');
 const key=JSON.stringify(ink),g=art?.lastGuess,matching=g&&JSON.stringify(g.strokes)===key&&(g.mode??'auto')===mode;
 const alive=useRef(true),pending=useRef(false),lastRequest=useRef('');useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 useEffect(()=>{setMessage('');setChoose(false);},[key]);
 const resultLine=(r:any)=>r.label?guessLine(r.label):r.reason==='more-ink'?'Add a little more drawing first.':r.reason==='number-range'?'Try a number from zero to one hundred.':r.candidates?.length?'Could it be one of these?':'I am not sure yet. What did you draw?';
 const guess=async()=>{if(pending.current)return;const request=mode+key;if(matching&&lastRequest.current===request){onSpeak(resultLine(g));return;}pending.current=true;setMessage('Thinking…');setChoose(false);try{const p=await act({kind:'art_guess',strokes:ink,mode});if(!alive.current)return;if(!p){setMessage('Not saved yet. Try Guess again.');return;}lastRequest.current=request;const text=resultLine(p.art.lastGuess);setMessage(text);onSpeak(text);}catch{if(alive.current)setMessage('The guess could not be saved. Your drawing is still here.');}finally{pending.current=false;}};
 const label=async(label:string)=>{if(pending.current)return;pending.current=true;try{const p=await act({kind:'art_label',guessId:g.id,label});if(p&&alive.current){setChoose(false);setMessage('Thanks for telling me!');onSpeak(labelLine(label));}}catch{if(alive.current)setMessage('Not saved yet. Try telling me again.');}finally{pending.current=false;}};
 const tile=(x:string)=><Button variant="outline" disabled={busy} key={x} aria-label={labelName(x)} onClick={()=>void label(x)}><span className="guessed-symbol">{DOODLE_ICONS[x as keyof typeof DOODLE_ICONS]||x}</span><small>{labelName(x)}</small></Button>;
 return <div className="guess-panel"><div className="draw-tools"><NativeSelect aria-label="What to guess" value={mode} disabled={busy} onChange={e=>{setMode(e.target.value);setMessage('');setChoose(false);}}><NativeSelectOption value="auto">Anything</NativeSelectOption><NativeSelectOption value="letters">Letters · A a</NativeSelectOption><NativeSelectOption value="numbers">Numbers · 0–100</NativeSelectOption><NativeSelectOption value="pictures">Pictures</NativeSelectOption></NativeSelect><Button disabled={busy||!ink.length} onClick={()=>void guess()}>✨ Guess my drawing</Button></div>
 <p aria-live="polite">{matching?(g.childLabel?'You called it: '+(g.caseAmbiguous&&g.childLabel===g.label?'Letter '+g.label:labelName(g.childLabel))+'.':message||resultLine(g)):message||'Draw a letter, a number, or a picture. Then ask me to guess.'}</p>
 {matching&&!g.childLabel&&<>{g.label&&!choose&&<div className="draw-tools"><strong className="guessed-symbol">{DOODLE_ICONS[g.label as keyof typeof DOODLE_ICONS]||g.label}</strong><Button disabled={busy} onClick={()=>void label(g.label)}>Yes!</Button></div>}{!g.label&&<div className="art-labels">{g.candidates?.filter(validArtLabel).map(tile)}</div>}<Button variant="outline" disabled={busy} onClick={()=>{setChoose(x=>!x);onSpeak('What did you draw?');}}>I drew something else</Button></>}
 {matching&&!g.childLabel&&choose&&<><div className="draw-tools"><NativeSelect aria-label="My drawing was" value={labels} onChange={e=>setLabels(e.target.value)} disabled={busy}><NativeSelectOption value="upper">Uppercase letters</NativeSelectOption><NativeSelectOption value="lower">Lowercase letters</NativeSelectOption><NativeSelectOption value="numbers">Numbers</NativeSelectOption><NativeSelectOption value="pictures">Pictures</NativeSelectOption></NativeSelect></div><div className="art-labels">{(labels==='upper'?UPPER:labels==='lower'?LOWER:labels==='numbers'?DIGITS:PICTURE_LABELS).map(tile)}</div>{labels==='numbers'&&<div className="draw-tools"><Input aria-label="My number from 0 to 100" inputMode="numeric" maxLength={3} value={number} onChange={e=>setNumber(e.target.value)} disabled={busy}/><Button disabled={busy||!/^\d+$/.test(number)||!validArtLabel(number)} onClick={()=>void label(number)}>That number</Button></div>}<Button disabled={busy} variant="outline" onClick={()=>void label('something else')}>Something else</Button></>}
 <small>For the best guess, draw one picture at a time. Save it before clearing the pad for a new picture. You can still draw anything you like! Letters A–Z/a–z and numbers 0–100 work too. Leave space between digits. No points lost!</small>
 <details><summary>For grown-ups: how guesses work</summary><small>Local handwriting prototypes recognize letters/digits alongside picture examples, including faces, people and trees. Separate person-like faces can suggest a group or family picture, but the app never infers who anyone is. This is a fallible guess, not a handwriting grade or a general word reader. Case and similar symbols can be ambiguous. Guesses and child labels stay on your server for debugging, not automatic training. Picture model derived from Google Quick, Draw!, CC BY 4.0. <a href="https://github.com/googlecreativelab/quickdraw-dataset" target="_blank" rel="noreferrer">Dataset and credit</a>.</small></details>
 </div>;
}
function Picture({mission}:{mission:any}){
 const model=MISSIONS[mission.index];return <svg viewBox="0 0 100 100" className="mission-picture" aria-label={'Your '+model.name.toLowerCase()+' drawing'} role="img">{mission.strokes.flatMap((ink:Point[][],i:number)=>fitInk(ink,model.parts[i][1] as number[]).map((s:number[][],j:number)=><polyline key={i+':'+j} points={s.map(p=>p.join(',')).join(' ')} fill="none" stroke={['#00867d','#986421','#00867d'][i%3]} strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"/>))}</svg>;
}
export function DrawingMissions({art,act,busy,onSpeak}:Props){
 const m=art?.mission;
 const [error,setError]=useState('');
 const alive=useRef(true);useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 const start=async()=>{try{const p=await act({kind:'art_start'});if(!p&&alive.current)setError('Not saved yet. Try again.');}catch{if(alive.current)setError('Could not start. Please try again.');}};
 return <div className="drawing-missions"><h1>Drawing missions</h1>{!m?<><p>Build a picture, one shape at a time. Your lines stay yours!</p><div className="mission-preview">{MISSIONS.map(x=><span key={x.id}>{x.icon}</span>)}</div><Button disabled={busy} onClick={()=>void start()}>Draw a tree →</Button></>:m.complete?<><h2>{MISSIONS[m.index].name} complete!</h2><Picture mission={m}/><p>Your picture is saved. {art.completed} drawing{art.completed===1?'':'s'} made!</p><Button disabled={busy} onClick={()=>void start()}>Next: {MISSIONS[art.completed%MISSIONS.length].name} →</Button></>:<MissionPart key={m.id+':'+m.part} mission={m} act={act} busy={busy} onSpeak={onSpeak}/>}
 <p role="status">{error}</p><small>Shape-building practice, not an art grade. Wobbles and different sizes are welcome.</small></div>;
}
function MissionPart({mission:m,act,busy,onSpeak}:{mission:any,act:Props['act'],busy:boolean,onSpeak:Props['onSpeak']}){
 const model=MISSIONS[m.index],kind=model.parts[m.part][0] as keyof typeof PARTS,part=PARTS[kind];
 const [ink,setInk]=useState<Point[][]>([]),[draft,setDraft]=useState<Point[]>([]),[message,setMessage]=useState(''),[example,setExample]=useState(false);
 const inkTools=useInkTools(ink,setInk);
 const held=useRef<number|null>(null),line=useRef<Point[]>([]),alive=useRef(true),locked=useRef(false);
 useEffect(()=>{alive.current=true;onSpeak(part.prompt);return()=>{alive.current=false;};},[]);
 const point=(e:React.PointerEvent<SVGSVGElement>):Point=>{const r=e.currentTarget.getBoundingClientRect(),size=Math.min(r.width,r.height);return [Math.max(0,Math.min(100,(e.clientX-r.x-(r.width-size)/2)*100/size)),Math.max(0,Math.min(100,(e.clientY-r.y-(r.height-size)/2)*100/size))];};
 const finish=(p?:Point)=>{if(held.current===null)return;const s=p?[...line.current,p]:line.current;held.current=null;line.current=[];setDraft([]);if(s.length)setInk(i=>[...i,s]);};
 const check=async(keep=false)=>{if(locked.current)return;locked.current=true;setMessage('Saving…');try{const p=await act({kind:'art_part',missionId:m.id,part:m.part,strokes:ink,example,keep});if(!p){if(alive.current)setMessage('Not saved yet. Try Check drawing again.');return;}if(alive.current){const result=p.art.mission.feedback;setMessage(result.message);if(!result.ok&&!result.kept)onSpeak(result.message);}if(p.art.mission.complete)onSpeak('Drawing complete!');}catch{if(alive.current)setMessage('Not saved yet. Your lines are still here. Try again.');}finally{locked.current=false;}};
 return <><div className="mission-heading"><strong>{model.icon} {model.name} · Part {m.part+1} of {model.parts.length}</strong><Button variant="outline" disabled={busy} aria-label="Hear mission instruction" onClick={()=>onSpeak(part.prompt)}>🔊</Button></div><p>{part.prompt}</p><div className="mission-work"><Picture mission={m}/><svg className="draw-pad" viewBox="0 0 100 100" role="img" aria-label={'Draw a '+part.name}
 onPointerDown={e=>{if(busy||held.current!==null||!inkTools.erasing&&(ink.reduce((n,s)=>n+s.length,0)>4200||ink.length>=100))return;e.preventDefault();held.current=e.pointerId;if(inkTools.erasing)inkTools.begin(point(e));else{inkTools.penStarted();line.current=[point(e)];setDraft(line.current);}e.currentTarget.setPointerCapture(e.pointerId);}}
 onPointerMove={e=>{if(held.current!==e.pointerId||busy)return;if(inkTools.erasing)inkTools.move(point(e));else if(line.current.length<699){line.current=[...line.current,point(e)];setDraft(line.current);}}}
 onPointerUp={e=>{if(held.current!==e.pointerId)return;if(inkTools.erasing){inkTools.move(point(e));inkTools.end();held.current=null;}else finish(point(e));}} onPointerCancel={()=>{if(inkTools.erasing){held.current=null;inkTools.end();}else finish();}}>
 {[...ink,draft].map((s,i)=><polyline key={i} points={s.map(p=>p.join(',')).join(' ')} fill="none" stroke="#007e83" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"/>)}{inkTools.cursor}</svg></div>
 <div className="draw-tools">{inkTools.controls(busy)}<Button variant="outline" disabled={busy||!inkTools.canUndo} onClick={()=>{inkTools.undo();setMessage('');}}>Undo</Button><Button variant="outline" disabled={busy} onClick={()=>{setInk([]);inkTools.reset();setMessage('');}}>Clear part</Button><Button disabled={busy||!ink.length} onClick={()=>void check()}>Check drawing →</Button><Button variant="outline" disabled={busy} onClick={()=>setExample(x=>!x)}>Example</Button></div>
 {(m.attempts||0)>=2&&<div className="draw-tools"><small>My shape checker can be wrong. You can keep your drawing and move on.</small><Button variant="outline" disabled={busy||!ink.length} onClick={()=>void check(true)}>Keep my version →</Button></div>}
 {example&&<div className="part-example"><small>One example. Draw it your way on the empty pad.</small><svg viewBox="0 0 100 100" aria-label={'Example '+part.name} role="img"><polyline points={part.path.map(p=>p.join(',')).join(' ')} fill="none" stroke="#007e83" strokeWidth="3" strokeLinejoin="round"/></svg></div>}
 <p aria-live="polite">{message||'Draw freely. Tap Check when this part is ready.'}</p></>;
}
