'use client';
import {useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {launchPlayer,PLAYER_KEY,PARENT_PLAYER_KEY,chooseDevicePlayer} from '@/lib/player-launch.mjs';
import {ParentSettings} from './parent-settings';
import {Progress} from '@/components/ui/progress';
import {Slider} from '@/components/ui/slider';
import {gamesFor} from '@/lib/math.mjs';
import {scheduleAdvance} from '@/lib/auto-advance.mjs';
import {createSaveClient} from '@/lib/save-client.mjs';
import {createAppRefresh} from '@/lib/app-refresh.mjs';
import {say,stopVoice,chime,instruction} from '@/lib/audio';
import {Drawing} from './drawing';
import {Reading} from './reading';
import {Planning} from './planning';
import {Counting} from './counting';
import {Grouping} from './grouping';
import {PatternRepair} from './pattern-repair';
import {CookieDivision} from './cookie-division';
import {toggleRemoval} from '@/lib/play-practice.mjs';
type Profile=any;
export default function Home(){
 const [player,setPlayer]=useState('beginner'),[p,setP]=useState<Profile>(null),[tab,setTab]=useState('play'),[studio,setStudio]=useState(false),[open,setOpen]=useState(false),[saving,setBusy]=useState(false),[error,setError]=useState(''),[sound,setSound]=useState(true),[removed,setRemoved]=useState<number[]>([]),[value,setValue]=useState<number|null>(null);
 const [refreshing,setRefreshing]=useState(false),busy=saving||refreshing;
 const [parentOpen,setParentOpen]=useState(false);
 const refreshView=useRef<any>(null),appRefresh=useRef<any>(null);
 const [notice,setNotice]=useState(''),[initialized,setInitialized]=useState(false);
 const locked=useRef(false),live=useRef({p,player}),lastVoice=useRef(''),client=useRef<any>(null);live.current={p,player};
 const event=(kind:string,name='',detail='')=>{void fetch('/api/'+live.current.player+'/events',{method:'POST',headers:{'Content-Type':'application/json',...client.current?.headers()},body:JSON.stringify({kind,name,detail})}).catch(()=>{});};
 if(!client.current)client.current=createSaveClient({fetch:(...args:Parameters<typeof fetch>)=>fetch(...args),apply:(data:any)=>{live.current.p=data;setP(data);},status:(s:any)=>{if('busy' in s){locked.current=s.busy;setBusy(s.busy);}if('error' in s)setError(s.error);if('notice' in s)setNotice(s.notice);},report:(name:string,detail:any)=>event('sync',name,JSON.stringify(detail))});
 const speak=(text:string|string[])=>void say(text,e=>event('voice',Array.isArray(text)?text.join(' | '):text,e));
 refreshView.current={player,tab,open,sound,draft:tab==='draw'||tab==='reading'&&!!p?.reading?.session&&!p.reading.session.finished||tab==='play'&&open&&!!p?.session&&!p.session.finished&&!p.session.result};
 if(!appRefresh.current)appRefresh.current=createAppRefresh({read:()=>({...refreshView.current,href:location.href,saving:client.current.busy}),fetch:(...args:Parameters<typeof fetch>)=>fetch(...args),confirm:(message:string)=>window.confirm(message),navigate:(url:string)=>location.replace(url),stop:stopVoice,status:(s:any)=>{setRefreshing(s.busy);if('error' in s)setError(s.error);if('notice' in s)setNotice(s.notice);},report:(name:string,detail:any)=>event('sync',name,JSON.stringify(detail))});
 const refresh=()=>void appRefresh.current.refresh();
 const reconnect=()=>{stopVoice();void client.current.refresh('manual');};
 useEffect(()=>{const params=new URLSearchParams(location.search),tab=params.get('tab'),drawingStudio=params.get('studio')==='1';let stored=null,parentChoice=null;try{stored=localStorage.getItem(PLAYER_KEY);parentChoice=localStorage.getItem(PARENT_PLAYER_KEY);}catch{}const id=launchPlayer(location.search,stored,parentChoice);setPlayer(id);try{localStorage.setItem(PLAYER_KEY,id);}catch{}setStudio(drawingStudio);if(drawingStudio)setTab('draw');else if(tab&&['play','reading','draw','planning'].includes(tab))setTab(tab);setSound(params.get('quiet')!=='1');setInitialized(true);},[]);
 useEffect(()=>{if(!initialized)return;live.current={p:null,player};setP(null);const url=new URL(location.href);setOpen(url.searchParams.get('resume')==='1'&&url.searchParams.get('player')===player);stopVoice();void client.current.select(player);event('open');url.searchParams.set('player',player);url.searchParams.delete('resume');history.replaceState(null,'',url);return()=>client.current.dispose();},[player,initialized]);
 useEffect(()=>{if(!notice||busy)return;const timer=setTimeout(()=>setNotice(''),3000);return()=>clearTimeout(timer);},[notice,busy]);
 useEffect(()=>{const report=(e:ErrorEvent)=>event('error','runtime',e.message);window.addEventListener('error',report);return()=>window.removeEventListener('error',report);},[]);
 const act=(input:any)=>appRefresh.current.busy?Promise.resolve(null):client.current.action(input);
 const run=(input:any)=>void act(input).catch(()=>{});
 const start=async(game:string)=>{stopVoice();const data=await act({kind:'start',game});if(data)setOpen(true);return data;};
 const s=p?.session,q=s?.question,older=player==='explorer';
 useEffect(()=>{if(!open||tab!=='play')return;const frame=requestAnimationFrame(()=>document.querySelector('.playboard')?.scrollIntoView({block:'start'}));return()=>cancelAnimationFrame(frame);},[open,tab]);
 const [visible,setVisible]=useState(true);
 const advanceState=useRef<any>(null);
 advanceState.current={session:s,player,revision:p?.revision,active:open&&tab==='play'&&!busy&&!error&&visible&&!parentOpen};
 useEffect(()=>{const update=()=>{const visible=document.visibilityState==='visible';if(visible)void client.current.refresh('resume');setVisible(visible);};const online=()=>void client.current.refresh('online');const restored=(e:PageTransitionEvent)=>{if(e.persisted)update();};document.addEventListener('visibilitychange',update);window.addEventListener('online',online);window.addEventListener('pageshow',restored);return()=>{document.removeEventListener('visibilitychange',update);window.removeEventListener('online',online);window.removeEventListener('pageshow',restored);};},[]);
 useEffect(()=>scheduleAdvance({...advanceState.current,read:()=>({...advanceState.current,active:advanceState.current.active&&!locked.current&&document.visibilityState==='visible'}),advance:()=>run({kind:'next',auto:true})}),[q?.id,s?.result,s?.finished,p?.revision,player,open,tab,busy,error,visible,parentOpen]);
 useEffect(()=>{setRemoved([]);setValue(null);},[q?.id,player]);
 useEffect(()=>{if(tab!=='play'||!open||!q||s?.finished||s?.result||!sound)return;const key=player+':'+q.id;if(lastVoice.current===key)return;lastVoice.current=key;speak(instruction(q));return()=>stopVoice();},[q?.id,open,s?.finished,s?.result,sound,player,tab]);
 useEffect(()=>{if(s?.result?.ok&&sound)chime();},[s?.result]);
 // A small imperative interface; unsupported browsers simply use the visible UI.
 useEffect(()=>{
  const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();
  const tools=[
   {name:'read_math_practice',description:'Read the selected player, fixed number ceiling, progress and current game. Does not reveal answers.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({player:live.current.player,ceiling:live.current.p?.ceiling,lessons:live.current.p?.lessons,game:live.current.p?.session?.game,round:live.current.p?.session?.round})},
   {name:'start_math_game',description:'Start a fresh six-question game for the currently selected player, replacing any unfinished round without removing earned points.',inputSchema:{type:'object',properties:{game:{type:'string',enum:gamesFor({id:player}).map(g=>g.id)}},required:['game'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:any)=>{if(!input||Object.keys(input).some(k=>k!=='game')||!gamesFor({id:live.current.player}).some(g=>g.id===input.game))throw Error('Choose a listed game.');const data=await start(input.game);if(!data)throw Error('Wait for the current action.');return{game:data.session.game,round:1,ceiling:data.ceiling};}}
  ];for(const tool of tools){try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(e=>event('error','webmcp',String(e)));}catch(e){event('error','webmcp',String(e));}}return()=>lifecycle.abort();
 },[player]);
 const answer=(a:number|string)=>{stopVoice();run({kind:'answer',answer:a,questionId:q.id,...(q.kind==='subtract'?{removedIndices:removed}:{})});};
 const equation=q?.kind==='subtract'?<>{q.total} − {q.remove} = <em>?</em></>:<>{q?.blank===0?<em>?</em>:q?.a} {q?.operator||'+'} {q?.blank===1?<em>?</em>:q?.b} = {q?.blank===2?<em>?</em>:q?.total}</>;
 const drawingView=(standalone=false)=><Drawing key={player} player={player} studio={standalone} art={p?.art} act={act} traceNext={p?.traceNext} shapeNext={p?.shapeNext} saved={p?.drawing} savedSpace={p?.drawingSpace} busy={busy} report={(name,detail)=>event('drawing',name,detail)} onSave={async ink=>{if(!await act({kind:'drawing',strokes:ink,space:'wide-160'}))throw Error('Please try saving again.');}} onTrace={async(digit,ink,practice)=>{const saved=await act({kind:'trace',digit,strokes:ink,practice});if(!saved)throw Error('Please try saving again.');if(sound)chime();}} onShape={async(shape,ink,practice)=>{if(!await act({kind:'shape',shape,strokes:ink,practice}))throw Error('Please try saving again.');if(sound)chime();}} onSpeak={text=>{if(sound)speak(text);}}/>;
 if(!initialized)return <main className="park drawing-app"><p>Opening your canvas…</p></main>;
 if(studio)return <main className="park drawing-app"><header className="studio-top"><div className="brand"><b className="drawing-logo" aria-hidden="true">✎</b><strong>Guess My <span>Drawing</span></strong></div><div className="player-tools"><Button className="sound" variant="outline" aria-label={sound?'Mute automatic sound':'Turn sound on'} onClick={()=>{stopVoice();setSound(!sound)}}>{sound?'🔊':'🔇'}</Button><Button variant="outline" disabled={busy} onClick={refresh} aria-label="Refresh app and load updates">↻ {refreshing?'Refreshing…':saving?'Saving…':'Refresh'}</Button></div></header>{error&&<div className="error" role="alert">{error} <Button variant="outline" disabled={busy} onClick={reconnect}>Reconnect saved drawing</Button></div>}{!p?<p>Opening your canvas…</p>:drawingView(true)}<footer>Draw freely · Your pictures stay on your server</footer></main>;
 return <main className={'park '+(older?'challenge-park':'')}><div className="player-identity" data-player={player} aria-label="Active player"><small>PLAYING AS</small><strong>{initialized?(player==='admin'?'Admin · Admin':older?'Explorer':'Beginner'):'Opening…'}</strong></div><header className="top"><div className="brand"><b className="logo">3<span>● ● ●</span></b><strong>number<span>park</span></strong></div><div className="player-tools"><span className="xp" title={tab==='reading'?'Reading practice stars':tab==='planning'?'Planning badges':'Math stars'}>{tab==='reading'?'📖 ★ ':tab==='planning'?'🏅 ':'★ '}{tab==='reading'?(p?.reading?.stars||0):tab==='planning'?(p?.planning?.badges||0):(p?.xp||0)}</span><Button className="sound" variant="outline" aria-label={sound?'Mute automatic sound':'Turn sound on'} onClick={()=>{stopVoice();setSound(!sound)}}>{sound?'🔊':'🔇'}</Button></div></header>
 {player==='admin'&&<p className="admin-note">ADMIN · SEPARATE TEST SAVE</p>}
 <div className="connection-tools"><span role="status" aria-live="polite">{notice}</span><Button variant="outline" disabled={busy} onClick={refresh} aria-label="Refresh app and load updates">↻ {refreshing?'Refreshing…':saving?'Saving…':'Refresh'}</Button></div>
 {error&&<div className="error" role="alert">{error} <Button variant="outline" disabled={busy} onClick={reconnect}>Reconnect saved progress</Button></div>}
 <Tabs value={tab} onValueChange={v=>{stopVoice();setTab(String(v));}}><TabsList className="park-tabs"><TabsTrigger value="play">🎲 Play</TabsTrigger><TabsTrigger value="planning">🗺️ Plan & Play</TabsTrigger><TabsTrigger value="reading">📖 Reading</TabsTrigger><TabsTrigger value="draw">✏️ Draw & trace</TabsTrigger></TabsList>
 <TabsContent value="play">{!p?<p>Opening your park…</p>:open&&s?<section className="playboard"><div className="lesson-bar"><Button variant="outline" onClick={()=>{stopVoice();setOpen(false)}}>← Park</Button><Progress value={s.finished?100:s.round/6*100} aria-label="Lesson progress"/><span>{s.finished?6:s.round+1} / 6</span><Button variant="outline" aria-label="Hear instruction again" onClick={()=>speak(s.finished?'Lesson complete.':instruction(q))}>🔊</Button></div>
 {s.finished?<div className="lesson-done"><div className="sticker">🌟</div><h1>{older?'Mission complete!':'A little win!'}</h1><p>{s.correct} out of 6 correct · {s.independent} without help</p><p>{older?'New puzzles. Your own challenge level.':'Another round. Same little numbers.'}</p><Button className="big-play" onClick={()=>void start(s.game).catch(()=>{})} disabled={busy}>Play again →</Button></div>:<>
 <p className="eyebrow">{gamesFor(p).find(g=>g.id===s.game)?.title||'Warm-up'} · {q.kind==='pattern'?'PATTERN LEVEL '+(q.level||1):older?(q.track?'CHALLENGE '+q.level:'WARM-UP'):'SMALL NUMBERS'}</p><h1>{q.kind==='cookies'?'Share the cookies!':q.kind==='multiply'?'Multiply!':q.kind==='factor'?'Which factor is missing?':q.kind==='skip'?'Where does the next jump land?':q.kind==='place'?(q.placeMode==='number'?'Build the number.':q.placeMode==='tens'?'How many tens?':'How many ones?'):q.kind==='count'?'How many?':q.kind==='pattern'?(q.mode==='repair'?'Repair the pattern!':q.mode==='missing'?'Find the missing picture.':q.mode==='pair'?'Which TWO come next?':'What comes next?'):q.kind==='line'?'Hop to the answer.':q.kind==='subtract'?'How many are left?':q.kind==='addobjects'?'How many altogether?':'Find the missing piece.'}</h1>
 {!['count','pattern','skip','place','cookies'].includes(q.kind)&&<div className="equation">{equation}</div>}
 {q.kind==='cookies'&&<CookieDivision key={q.id} q={q} draft={s.cookieDraft} disabled={busy} result={s.result} message={s.cookieMessage} helped={s.helped} place={draft=>run({kind:'cookie-place',questionId:q.id,draft})} check={guess=>run({kind:'cookie-check',questionId:q.id,...guess})} report={(name,detail)=>event('cookie',name,detail)}/>}
 {q.kind==='pattern'&&q.mode==='repair'&&<PatternRepair key={q.id} q={q} disabled={busy||!!s.result} result={s.result} onAnswer={answer} report={(name,detail)=>event('pattern',name,detail)}/>}
 {['pattern','skip'].includes(q.kind)&&q.mode!=='repair'&&<div className="pattern">{q.sequence.map((v:string|null,i:number)=><span className={v===null?'blank':''} key={i}>{v??'?'}</span>)}{q.mode!=='missing'&&<><span className="blank">?</span>{q.mode==='pair'&&<span className="blank">?</span>}</>}</div>}
 {q.kind==='place'&&<section className="place-puzzle" aria-label="Place value puzzle">{q.placeMode==='number'?<><p><strong>{q.tens} tens</strong> + <strong>{q.ones} ones</strong></p><div className="place-model" aria-hidden="true"><div>{Array.from({length:q.tens},(_,i)=><span className="ten-rod" key={i}/>)}</div><div>{Array.from({length:q.ones},(_,i)=><span className="one-block" key={i}/>)}</div></div></>:<div className="equation">{q.total}</div>}</section>}
 {q.kind==='count'&&<Counting key={q.id} q={q} disabled={busy||!!s.result} speak={text=>{if(sound)speak(text);}}/>}
 {q.kind==='addobjects'&&<Grouping key={q.id} q={q} disabled={busy||!!s.result} speak={text=>{if(sound)speak(text);}} report={(name,detail)=>event('group',name,detail)}/>}
 {q.kind==='subtract'&&<><p>Take away {q.remove}. Tap again to put it back.</p><div className="objects subtraction">{Array.from({length:q.total},(_,i)=><Button aria-label={(removed.includes(i)?'Put back object ':'Take away object ')+(i+1)} key={i} disabled={busy||!!s.result} className={'token '+(removed.includes(i)?'removed':'')} onClick={()=>setRemoved(r=>toggleRemoval(r,i))}>{q.object}</Button>)}</div></>}
 {q.kind==='cookies'?null:q.kind==='line'?<div className="numberline"><output>{value===null?'Slide the button':value}</output><Slider aria-label="Answer on the number line" min={0} max={13} step={1} onPointerDownCapture={()=>{if(!busy&&!s.result&&value===null)setValue(0)}} onKeyDownCapture={e=>{if(!busy&&!s.result&&value===null&&(e.key.startsWith('Arrow')||e.key==='Home'||e.key==='End'))setValue(0)}} value={[value??0]} disabled={busy||!!s.result} onValueChange={v=>setValue(Array.isArray(v)?v[0]:v)}/><div className="ticks">{Array.from({length:14},(_,i)=><span key={i} style={{left:(i/13*100)+'%'}}>{i}</span>)}</div><Button disabled={busy||!!s.result||value===null} className="big-play" onClick={()=>answer(value!)}>Check ✓</Button></div>:
 q.mode==='repair'?null:<div className="answers">{q.options.map((n:number|string)=><Button key={n} className={'answer '+(s.result&&s.result.answer===n?'correct':'')} disabled={busy||!!s.result} onClick={()=>answer(n)}>{n}</Button>)}</div>}
 <div className={'result '+(s.result?s.result.ok?'win':'learn':'')} aria-live="polite">{s.result?<><strong>{s.result.ok?'You got it!':'Let’s look together.'}</strong><span>{s.result.ok?'+'+s.result.xp+' stars':'The answer is '+s.result.answer+'.'}</span><Button disabled={busy} onClick={()=>run({kind:'next'})}>{s.result.ok?'Moving on…':s.round===5?'Finish round':'Continue'} →</Button></>:s.helped?<><span>{q.kind==='cookies'?q.mode==='snack'?'First take away the cookies Buddy ate. Then share the rest.':q.mode==='remainder'?'Make full, equal plates. Count the cookies left over.':'Give one cookie to each plate, then go around again.':`Let’s use ${q.answer}. This one is practice with help.`}</span></>:<p>Take your time. No timer.</p>}</div>
 {!s.result&&<Button variant="ghost" disabled={busy||s.helped} onClick={()=>{run({kind:'hint'});if(q.kind==='cookies'&&sound)speak(q.mode==='snack'?'First take away the cookies Buddy ate. Then share the rest.':q.mode==='remainder'?'Make full, equal plates. Count the cookies left over.':'Give one cookie to each plate, then go around again.')}}>Help me</Button>}
 </>}
 </section>:<><section className="welcome"><div><p className="eyebrow">{older?'YOUR OWN MATH MISSIONS':'THE SAME LITTLE NUMBERS. NEW WAYS TO PLAY.'}</p><h1>Let’s play, {p.name}.</h1><p>{older?'Times tables, bigger sums and number puzzles. Each skill adjusts as you play.':'No jump to big numbers. Every round stays within 13.'}</p><Button className="big-play" disabled={busy} onClick={()=>void start('mix').catch(()=>{})}>{older?'🚀 Start a math mission':'🎲 Play a little lesson'}</Button>{s&&!s.finished&&<Button variant="ghost" onClick={()=>{lastVoice.current='';setOpen(true)}}>Resume my round →</Button>}</div><div className="number-stack" aria-hidden="true"><b>{older?'×':'1'}</b><b>{older?'7':'2'}</b><b>{older?'8':'3'}</b></div></section><section className="game-grid">{gamesFor(p).map((g,i)=><Button key={g.id} className={'game-card game-'+i} variant="outline" disabled={busy} onClick={()=>void start(g.id).catch(()=>{})}><span className="game-icon">{g.icon}</span><strong>{g.title}</strong><span>{g.description}</span><b className="card-play">{p.completed[g.id]?'Play again':'Play'} →</b></Button>)}</section></>}</TabsContent>
 <TabsContent value="reading">{p&&<Reading key={player} player={player} reading={p.reading} act={act} busy={busy} sound={sound} active={tab==='reading'&&!parentOpen} error={error} report={(name,detail)=>event('reading',name,detail)}/>}</TabsContent>
 <TabsContent value="planning">{p&&<Planning key={player} player={player} planning={p.planning} act={act} busy={busy} sound={sound} active={tab==='planning'&&!parentOpen} error={error} report={(name,detail)=>event('planning',name,detail)}/>}</TabsContent>
 <TabsContent value="draw">{p&&drawingView()}</TabsContent>
 </Tabs><footer>On your server · Separate family saves · No ads or strangers<ParentSettings player={player} open={parentOpen} busy={busy||!initialized} onOpenChange={v=>{stopVoice();setParentOpen(v);}} onChoose={id=>chooseDevicePlayer({id,current:player,saving:client.current.busy||appRefresh.current.busy,draft:refreshView.current.draft,confirm:(message:string)=>window.confirm(message),storage:localStorage,report:(detail:any)=>event('profile','parent_switch',JSON.stringify(detail)),apply:(next:string)=>{stopVoice();setP(null);setOpen(false);setTab('play');lastVoice.current='';const url=new URL(location.href);url.searchParams.set('player',next);url.searchParams.set('tab','play');url.searchParams.delete('resume');history.replaceState(null,'',url);setPlayer(next);}})}/></footer></main>;
}
