'use client';
import {useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Slider} from '@/components/ui/slider';
import {Progress} from '@/components/ui/progress';
import {PACKS,soundKey,wordKey} from '@/lib/reading.mjs';
import {readingAudio} from '@/lib/reading-audio';
import {chime,stopVoice} from '@/lib/audio';

export function Reading({reading:r,player,act,busy,sound,active,error,report}:{reading:any,player:string,act:(input:any)=>Promise<any>,busy:boolean,sound:boolean,active:boolean,error:string,report:(name:string,detail:string)=>void}){
 const s=r?.session,q=s?.questions[s.round],done=!!q?.result?.ok;
 const [slots,setSlots]=useState<string[]>([]),[selected,setSelected]=useState(0),[progress,setProgress]=useState(0),[playing,setPlaying]=useState(false),[highlight,setHighlight]=useState(-1),[message,setMessage]=useState(''),[adult,setAdult]=useState(false),[visible,setVisible]=useState(true);
 const [ghost,setGhost]=useState<{letter:string,x:number,y:number}|null>(null);
 const audio=useRef<AbortController|null>(null),joining=useRef(false),drag=useRef<any>(null),suppress=useRef(false),gaps=useRef<(HTMLButtonElement|null)[]>([]),latest=useRef({busy,active,error,q});latest.current={busy,active,error,q};
 const stop=()=>{audio.current?.abort();audio.current=null;setPlaying(false);setHighlight(-1);};
 const play=async(keys:string[])=>{
  stopVoice();audio.current?.abort();const c=new AbortController();audio.current=c;setPlaying(true);setMessage('');
  const ok=await readingAudio(keys,c.signal,i=>setHighlight(i),(name,detail)=>report('voice',JSON.stringify({questionId:q?.id,name,detail})));
  if(audio.current!==c||c.signal.aborted)return false;
  setPlaying(false);setHighlight(-1);if(!ok)setMessage('Sound did not play. Tap Hear again to retry.');return ok;
 };
 const prompt=()=>!q?[]:q.kind==='listen'?[q.prompt,soundKey(q.target)]:['build','change'].includes(q.kind)?[q.prompt,wordKey(q.word)]:[q.prompt];
 const send=(kind:string,extra:any={})=>act({kind,questionId:q.id,...extra});
 useEffect(()=>{const update=()=>{const v=document.visibilityState==='visible';setVisible(v);if(!v)stop();};document.addEventListener('visibilitychange',update);return()=>{audio.current?.abort();document.removeEventListener('visibilitychange',update);};},[]);
 useEffect(()=>{setSlots(q?.kind==='change'?[...q.from]:Array(q?.word?.length||0).fill(''));setSelected(0);setProgress(0);setAdult(false);setMessage('');joining.current=false;setGhost(null);drag.current=null;if(active&&q&&!q.result?.ok&&!s.finished&&sound&&document.visibilityState==='visible')void play(prompt());return()=>audio.current?.abort();},[q?.id,active,player]);
 useEffect(()=>{if(!sound)stop();},[sound]);
 useEffect(()=>{
  if(!active||!visible||busy||error||playing||!done||s?.finished)return;
  const id=q.id,timer=setTimeout(()=>{const v=latest.current;if(!v.busy&&!v.error&&v.active&&v.q?.id===id&&v.q.result?.ok&&document.visibilityState==='visible')void send('reading_next');},1100);
  return()=>clearTimeout(timer);
 },[q?.id,done,active,visible,busy,error,playing,s?.finished]);
 useEffect(()=>{if(done&&sound&&active)chime();},[q?.id,done]);
 const submit=async(answer:string,observer?:string)=>{if(latest.current.busy||done)return;stop();return send('reading_answer',{answer,...(observer?{observer}:{})});};
 const hearSound=async(index:number)=>{if(busy||done||playing)return;const letters=q.kind==='sounds'?q.letters:[...q.word];if(await play([soundKey(letters[index])])){const data=await send('reading_sound',{index});const saved=data?.reading?.session?.questions[s.round];if(q.kind==='sounds'&&saved?.id===q.id&&saved.heard.length===letters.length)await send('reading_answer',{answer:'done'});}};
 const model=async()=>{if(busy||done)return;const data=await send('reading_hint');if(!data)return;const keys=q.kind==='listen'?[soundKey(q.target)]:q.word?[...[...q.word].map(soundKey),wordKey(q.word)]:[q.text];await play(keys);};
 const join=async()=>{if(joining.current||busy||done||playing)return;joining.current=true;setProgress(100);if(await play([...[...q.word].map(soundKey),wordKey(q.word)]))await submit('done');else setProgress(0);joining.current=false;};
 const place=(letter:string,index=selected)=>{if(busy||done||joining.current)return;const next=[...slots];next[index]=letter;setSlots(next);setSelected(Math.max(0,next.findIndex(x=>!x)));report('place',JSON.stringify({questionId:q.id,letter,index,method:drag.current?'drag':'tap'}));if(next.every(Boolean)){void submit(next.join('')).then(data=>{if(data&&latest.current.active&&latest.current.q?.id===q.id)void play([soundKey(letter)]);});}else{void play([soundKey(letter)]);}};
 if(!r||!s||s.finished)return <section className="playboard reading-home"><p className="eyebrow">READING PARK · START SMALL</p><div className="reading-garden" aria-hidden="true">{r?.lessons?'🌳':'🌱'}</div><h1>{s?.finished?'Your reading garden grew!':'Let’s grow some words.'}</h1><p>Hear letters and words. Read together.</p><div className="reading-path">{PACKS.map((p,i)=><span key={p.name} className={i===(r?.level||0)?'current':''}>{i+1} · {p.name}</span>)}</div><Button disabled={busy} className="big-play" onClick={()=>void act({kind:'reading_start'})}>{s?.finished?'Grow another word':'Let’s read'} →</Button><p>★ {r?.stars||0} reading stars · {r?.lessons||0} little lessons</p><small>Browser narration uses letter names and example words. A grown-up should model the sounds and blending. Reading saves separately from math.</small>{r?.history?.length>0&&<details className="reading-notes"><summary>Grown-up progress</summary><p>{r.history.filter((h:any)=>h.kind==='read'&&h.independent).length} adult-confirmed unaided word reads; {r.history.filter((h:any)=>h.kind==='read'&&h.independent&&h.delayed).length} on next-day-or-later reviews. These are observations, not a reading-age score.</p></details>}</section>;
 const letters=q.kind==='sounds'?q.letters:[...(q.word||'')],heard=q.heard.length===letters.length;
 return <section className="playboard reading-play"><div className="lesson-bar"><span>🌱 {s.round+1} / {s.questions.length}</span><Progress value={(s.round+Number(done))/s.questions.length*100} aria-label="Reading lesson progress"/><Button variant="outline" disabled={busy} aria-label="Hear reading instruction again" onClick={()=>void play(prompt())}>🔊 Hear again</Button></div>
 <p className="reading-notes">Grown-up: model the sounds. Browser narration names the letters.</p><p className="eyebrow">{PACKS[s.level].name} · {q.kind==='sounds'?'MEET THE SOUNDS':q.kind==='listen'?'SOUND HUNT':q.kind==='blend'?'PUT SOUNDS TOGETHER':q.kind==='build'?'WORD BUILDER':q.kind==='change'?'WORD SWITCH':q.kind==='read'?(q.delayed?'REMEMBER THIS WORD?':'YOUR TURN TO READ'):'TINY STORY'}</p>
 <h1>{q.kind==='sounds'?'Meet your sound team.':q.kind==='listen'?'Find the sound.':q.kind==='blend'?'Put the sounds together.':q.kind==='build'?'Build the word.':q.kind==='change'?'Change one letter.':q.kind==='read'?'What does it say?':'Read a little story.'}</h1>
 {['sounds','blend'].includes(q.kind)&&<><div className={'sound-team '+(progress===100?'joined':'')}>{letters.map((l:string,i:number)=><Button key={i} className={'sound-stone '+(q.heard.includes(i)?'heard ':'')+(highlight===i?'speaking':'')} disabled={busy||playing||done} aria-label={'Hear sound '+l} onClick={()=>void hearSound(i)}>{l.toUpperCase()}{q.kind==='sounds'&&<small>{l}</small>}{q.heard.includes(i)&&<span className="sound-check">✓</span>}</Button>)}</div><p>{q.kind==='sounds'?'Tap each letter. Listen to its sound.':heard?'Slide the gold button to join the sounds.':'First, tap every sound.'}</p>{q.kind==='sounds'?<Button disabled={!heard||busy||done||playing} onClick={()=>void submit('done')}>Let’s play with them →</Button>:<div className="blend-control"><Slider aria-label="Slide to join sounds" value={[progress]} min={0} max={100} disabled={!heard||busy||done||playing} onValueChange={v=>{const n=Array.isArray(v)?v[0]:v;setProgress(n);if(n>=95)void join();}}/><Button variant="outline" disabled={!heard||busy||done||playing} onClick={()=>void join()}>Join sounds →</Button></div>}</>}
 {q.kind==='listen'&&<div className="sound-team">{q.options.map((l:string)=><Button className={'sound-stone '+(q.helped&&l===q.target?'heard':'')} key={l} disabled={busy||done} onClick={()=>void submit(l)}>{l.toUpperCase()}<small>{l}</small></Button>)}</div>}
 {['build','change'].includes(q.kind)&&<><p>{q.kind==='change'?'Tap a letter to take it out. Put a new one in.':'Drag letters into the spaces, or tap them.'}</p><div className="word-slots">{slots.map((l,i)=><Button variant="outline" ref={el=>{gaps.current[i]=el;}} key={i} aria-label={'Letter space '+(i+1)+(l?': '+l:'')} className={'letter-slot '+(selected===i?'selected':'')} disabled={busy||done} onClick={()=>{setSelected(i);setSlots(a=>a.map((x,j)=>j===i?'':x));}}>{l.toUpperCase()||'·'}</Button>)}</div>{q.helped&&<p className="word-model">Build {q.word.toUpperCase()}. We’ll do it together.</p>}<div className="letter-bank">{q.bank.map((l:string)=><Button className="bank-letter" key={l} disabled={busy||done} aria-label={'Place letter '+l} onPointerDown={e=>{if(busy||done)return;suppress.current=false;drag.current={letter:l,x:e.clientX,y:e.clientY,id:e.pointerId,moved:false};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{const d=drag.current;if(!d||d.id!==e.pointerId)return;if(Math.hypot(e.clientX-d.x,e.clientY-d.y)>7)d.moved=true;if(d.moved)setGhost({letter:l,x:e.clientX,y:e.clientY});}} onPointerUp={e=>{const d=drag.current;if(!d||d.id!==e.pointerId)return;if(d.moved){suppress.current=true;const index=gaps.current.findIndex(el=>{if(!el)return false;const r=el.getBoundingClientRect();return e.clientX>=r.left-18&&e.clientX<=r.right+18&&e.clientY>=r.top-24&&e.clientY<=r.bottom+24;});if(index>=0)place(l,index);else setMessage('Drop near a space, or tap a letter to put it in.');}drag.current=null;setGhost(null);}} onPointerCancel={()=>{drag.current=null;setGhost(null);suppress.current=true;}} onClick={()=>{if(suppress.current){suppress.current=false;return;}place(l);}}>{l.toUpperCase()}</Button>)}</div></>}
 {['read','story'].includes(q.kind)&&<><div className={'read-aloud '+(done?'read-success':'')}>{q.kind==='read'?q.word.toUpperCase():q.text.toUpperCase()}</div><p>Say it out loud. Your grown-up listens.</p>{!adult?<Button variant="outline" disabled={busy||done} onClick={()=>setAdult(true)}>Grown-up check</Button>:<div className="grownup-check"><strong>For the grown-up: did {player==='admin'?'your child':player==='beginner'?'Beginner':'Explorer'} read it before hearing the answer?</strong><div><Button disabled={busy||done} onClick={()=>void submit('alone','grownup')}>Read it independently</Button><Button variant="outline" disabled={busy||done} onClick={()=>void submit('together','grownup')}>Read it together</Button></div><small>No microphone or automatic speech grading. Helped reads stay practice.</small></div>}</>}
 {done&&<div className="reading-win" role="status">🌳 +{q.result.stars} reading {q.result.stars===1?'star':'stars'} · Moving on…</div>}
 {!done&&q.result?.ok===false&&<p className="reading-gentle" role="status">Let’s try it together. You can change your answer.</p>}
 {!done&&!['sounds','blend'].includes(q.kind)&&<Button variant="ghost" disabled={busy||playing} onClick={()=>void model()}>Teach me this one</Button>}
 <p className="reading-message" role="status">{message}</p>{ghost&&<div className="reading-ghost" style={{left:ghost.x,top:ghost.y}} aria-hidden="true">{ghost.letter.toUpperCase()}</div>}
 </section>;
}
