import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,writeFileSync,mkdirSync,readFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {execFileSync} from 'node:child_process';
import {publishPrepared,main} from '../public-sync.mjs';
import {privacyIssues,checkTree,denied,sanitize,replacements} from '../public-policy.mjs';
import {exportLive} from '../public-export.mjs';
function fixture(t){const dir=mkdtempSync(join(tmpdir(),'public-sync-test-'));t.after(()=>rmSync(dir,{recursive:true,force:true}));execFileSync('git',['init','-q',dir]);execFileSync('git',['-C',dir,'config','user.name','Test']);execFileSync('git',['-C',dir,'config','user.email','test@example.invalid']);return dir;}
test('identities, forbidden characters and binary metadata are refused with the file listed',()=>{for(const term of denied){assert.deepEqual(privacyIssues('image.png',Buffer.from('metadata: '+term.toUpperCase())),['image.png: forbidden identity or character term']);}});
test('runtime data, credentials and household hosts are refused',()=>{assert.ok(privacyIssues('.data/save.json',Buffer.from('{}')).length);assert.ok(privacyIssues('fixture.mjs',Buffer.from(['host','tail123','ts','net'].join('.'))).length);assert.ok(privacyIssues('fixture.mjs',Buffer.from('github_pat_'+'x'.repeat(40))).length);assert.deepEqual(privacyIssues('demo.mjs',Buffer.from("player='beginner'; name='Pip';")),[]);});
test('a privacy failure cannot call build, push or PR creation',t=>{const dir=fixture(t);writeFileSync(join(dir,'leak.txt'),denied[0]);execFileSync('git',['-C',dir,'add','.']);const calls=[];assert.throws(()=>publishPrepared({cwd:dir,base:'HEAD',branch:'public/test',gh:'gh',title:'Test',run:(exe,args)=>calls.push([exe,args])}),/leak.txt/);assert.equal(calls.length,1);assert.equal(calls[0][0],'git');assert.deepEqual(calls[0][1],['add','--all']);});
test('a failed build cannot push or open a PR',t=>{const dir=fixture(t);writeFileSync(join(dir,'safe.txt'),'synthetic');execFileSync('git',['-C',dir,'add','.']);const calls=[];assert.throws(()=>publishPrepared({cwd:dir,base:'HEAD',branch:'public/test',gh:'gh',title:'Test',run:(exe,args)=>{calls.push([exe,args]);if(exe==='npm')throw Error('build failed');}}),/build failed/);assert.equal(calls.some(([exe,args])=>args[0]==='push'||exe==='gh'),false);});
test('new commit messages are independently gated',t=>{const dir=fixture(t);writeFileSync(join(dir,'safe.txt'),'synthetic');execFileSync('git',['-C',dir,'add','.']);execFileSync('git',['-C',dir,'commit','-qm','Public base']);const base=execFileSync('git',['-C',dir,'rev-parse','HEAD']).toString().trim();writeFileSync(join(dir,'safe.txt'),'synthetic change');execFileSync('git',['-C',dir,'commit','-qam',denied[0]]);assert.deepEqual(checkTree(dir,base).issues,['commit messages: forbidden identity or character term']);});
test('known preset identifiers are mapped and unknown private text refuses export',t=>{const dir=fixture(t),source=join(dir,'sources'),repo=join(source,'number-park');mkdirSync(repo,{recursive:true});execFileSync('git',['init','-q',repo]);mkdirSync(join(repo,'lib'));writeFileSync(join(repo,'lib/game.mjs'),"export const host="+JSON.stringify(['host','tail123','ts','net'].join('.'))+";");execFileSync('git',['-C',repo,'add','.']);execFileSync('git',['-C',repo,'-c','user.name=Test','-c','user.email=test@example.invalid','commit','-qm','Synthetic source']);const ref=execFileSync('git',['-C',repo,'rev-parse','HEAD']).toString().trim();assert.throws(()=>exportLive({target:dir,sourceRoot:source,refs:{'number-park':ref}}),/games\/number-park\/lib\/game.mjs: private deployment host/);const [from,to]=replacements[0];assert.equal(sanitize(from),to.toLowerCase());});
test('CLI requires explicit SHAs and paths before creating any branch',()=>{assert.throws(()=>main([]),/live SHA/);assert.throws(()=>main(['--unknown','value']),/Unknown option/);});
test('a clean candidate completes every gate before pushing one branch and opening the requested PR',t=>{
 const dir=fixture(t);writeFileSync(join(dir,'safe.txt'),'base');execFileSync('git',['-C',dir,'add','.']);execFileSync('git',['-C',dir,'commit','-qm','Public base']);const base=execFileSync('git',['-C',dir,'rev-parse','HEAD']).toString().trim();writeFileSync(join(dir,'safe.txt'),'new synthetic code');const calls=[];
 const run=(exe,args,options)=>{calls.push([exe,args,options]);if(exe==='git'&&args[0]!=='push')execFileSync(exe,args,{cwd:dir});};
 publishPrepared({cwd:dir,base,branch:'public/synthetic',title:'Synthetic sync',gh:'/fixture/gh',run});
 const pushed=calls.findIndex(([exe,args])=>exe==='git'&&args[0]==='push'),pr=calls.findIndex(([exe])=>exe==='/fixture/gh');assert.ok(pushed>calls.findIndex(([exe,args])=>exe==='npm'&&args[0]==='test'));assert.ok(pr>pushed);assert.deepEqual(calls[pushed][1],['push','--set-upstream','origin','public/synthetic']);assert.equal(calls[pushed][2].env.GIT_CONFIG_VALUE_1,"!'/fixture/gh' auth git-credential");assert.equal(calls[pr][1].includes('Synthetic sync'),true);assert.equal(calls.some(([,args])=>args.includes('merge')),false);
});
test('a clean final tree cannot hide a privacy hit in an earlier new commit',t=>{
 const dir=fixture(t);const git=args=>execFileSync('git',args,{cwd:dir});writeFileSync(join(dir,'safe.txt'),'base');git(['add','.']);git(['commit','-qm','Public base']);const base=git(['rev-parse','HEAD']).toString().trim();writeFileSync(join(dir,'leak.txt'),denied[0]);git(['add','.']);git(['commit','-qm','Synthetic intermediate']);rmSync(join(dir,'leak.txt'));writeFileSync(join(dir,'safe.txt'),'new code');let pushed=false;
 assert.throws(()=>publishPrepared({cwd:dir,base,branch:'public/synthetic',title:'Synthetic sync',gh:'/fixture/gh',run:(exe,args)=>{if(exe==='git'&&args[0]!=='push')git(args);if(args[0]==='push')pushed=true;}}),/leak.txt/);assert.equal(pushed,false);
});

test('onboarding profile/cast/photo/learner/likeness manifests are always private regardless of the chosen data root',()=>{
 for(const file of ['private/book/profiles.json','private/book/cast.json','private/book/photos/child/image.jpg','private/learner/child.json','private/book/art/local-references.json'])assert.ok(privacyIssues(file,Buffer.from('{}')).some(x=>x.includes('forbidden runtime/private file')),file);
});
