import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import vm from 'node:vm';
const source=await readFile(new URL('../public/app.mjs',import.meta.url),'utf8');
function fixture(overrides={}){
 let button,identity,reloads=0,stops=0;const notes=[];
 const context={id:'beginner',profile:{name:'Beginner'},demo:false,busy:false,drawing:false,strokes:[],nameAnswer:'',readingInkError:'',readingInkQueue:Promise.resolve(),window:{confirm:()=>true},notice:x=>notes.push(x),coachVoice:{stop:()=>stops++},soccerAudio:{stop:()=>stops++},telemetry:{record:()=>{}},location:{reload:()=>reloads++},document:{querySelector:()=>identity,body:{prepend:b=>identity=b},head:{append(){}},createElement:()=>({dataset:{},setAttribute(){}})},app:{querySelector:s=>s==='.app-refresh'?button:{append:b=>button=b}},...overrides};
 vm.runInNewContext(source.slice(source.indexOf('function mountRefresh(){'),source.indexOf("document.addEventListener('keydown',e=>{"))+'\nmountRefresh();',context);
 return {context,button,notes,get identity(){return identity;},get reloads(){return reloads;},get stops(){return stops;}};
}
test('Name banner is unique and updates even when Refresh already exists',()=>{const f=fixture();assert.equal(f.identity.textContent,'Beginner');const original=f.identity;f.context.id='explorer';f.context.profile.name='Explorer';vm.runInNewContext('mountRefresh()',f.context);assert.equal(f.identity,original);assert.equal(f.identity.textContent,'Explorer');assert.equal(f.identity.dataset.player,'explorer');});
test('Refresh is mounted once in shared screens and explicitly in the labyrinth',async()=>{const f=fixture();assert.equal(f.button.textContent,'↻ Refresh');vm.runInNewContext('mountRefresh()',f.context);assert.match(source,/mazeClient.update\(profile,mazeMessage,busy\);\s+mountRefresh\(\)/);assert.match(source,/function bind\(\)\{mountRefresh\(\)/);await f.button.onclick();assert.equal(f.reloads,1);assert.equal(f.stops,2);});
test('Refresh does not interrupt a save or discard a cancelled unfinished answer',async()=>{const f=fixture({busy:true});await f.button.onclick();assert.equal(f.reloads,0);assert.equal(f.notes.length,1);const dirty=fixture({nameAnswer:'Fran',window:{confirm:()=>false}});await dirty.button.onclick();assert.equal(dirty.reloads,0);});
test('Refresh waits for queued writing and stays put if saving fails',async()=>{let finish;const f=fixture({readingInkQueue:new Promise(r=>finish=r)});const click=f.button.onclick();assert.equal(f.reloads,0);f.context.readingInkError='offline';finish();await click;assert.equal(f.reloads,0);assert.equal(f.button.disabled,false);assert.match(f.notes[0],/not saved/);});
