"""Compile the included CC0 RhosGFX SVGs into self-contained board icons."""
from pathlib import Path
import json
import re

chess = Path(__file__).resolve().parents[1] / "hub/public/chess"
palette = {"#1a1a1a":"#213b50", "#fff2d4":"#fffcf5", "#ffdfb5":"#e2eaf0",
           "#f4c38e":"#c8d7e2", "#eba969":"#c3d4e2", "#d1774b":"#557991",
           "#bb5938":"#3b5c75", "#9c3d29":"#29475f"}
compiled = {}
for source in sorted((chess / "pieces").glob("[wb][BKNPRQ].svg")):
    svg = source.read_text()
    styles = dict(re.findall(r'\.([\w-]+)\{([^}]+)\}', svg))
    svg = re.sub(r'<defs>.*?</defs>', '', svg)
    svg = re.sub(r' class="([^"]+)"', lambda m: ' style="' + ';'.join(styles[c] for c in m[1].split()) + '"', svg)
    svg = re.sub(r' (?:id|data-name)="[^"]*"', '', svg)
    for old, new in palette.items():
        svg = svg.replace(old, new)
    if source.stem[1] == "B":
        # Remove the chevron-shaped surface shadow so it cannot read as a second slit.
        svg = re.sub(r'<path d="M36 34\.94[^"<>]*"[^<>]*/>',
                     lambda m: '<path d="M17.47' + m[0].split('M17.47', 1)[1] if 'M17.47' in m[0] else '', svg)
        svg = svg.replace('</g></svg>', '<path d="M44 23 32 38" fill="none" stroke="#213b50" stroke-width="4.5" stroke-linecap="round"/></g></svg>')
    svg = svg.replace('<svg ', '<svg class="chess-piece" aria-hidden="true" ', 1)
    compiled[source.stem] = svg
(chess / "pieces.mjs").write_text('// Generated by scripts/build-chess-pieces.py. RhosGFX / CC0; see pieces/PROVENANCE.md.\nexport const PIECES = ' + json.dumps(compiled, indent=2) + ';\n')
print(f"Compiled {len(compiled)} piece icons")
