import test from 'node:test';
import assert from 'node:assert/strict';
import {fresh,act,question,GAMES,voiceLines} from '../lib/engine.mjs';
const send=(p,input)=>act(p,{...input,revision:p.revision,questionId:p.session?.q?.id});
test('Every activity receives its own instruction, not another game’s prompt',()=>{for(const [game,pattern] of [['asteroids',/picture/],['wordoku',/row and column/],['rhyme',/rhymes/],['sort',/cargo dock/],['cipher',/code key/]])assert.match(question(game,1,0).prompt,pattern);const p=fresh('admin');assert.match(send(p,{kind:'start',game:'pixel'}).line,/Paint anything/);});
function solve(p){const s=p.session,q=s.q;let draft;
 if(['builder','cipher','transform','orbit'].includes(s.game))draft=[...q.answer];
 if(s.game==='wordoku')draft=[...q.model];if(s.game==='train')draft=q.word.split(' ');if(s.game==='search')draft=q.path.map(String);if(s.game==='beats')draft=Array(Number(q.answer)).fill('beat');
 if(draft)send(p,{kind:'draft',draft});return send(p,{kind:'answer',answer:q.answer,durationMs:1200});
}
for(const game of GAMES.filter(g=>g.id!=='pixel'))test(`${game.name}: eight solvable rounds, single reward, reload, separate skill level`,()=>{
 let p=fresh('admin');send(p,{kind:'start',game:game.id});for(let i=0;i<8;i++){assert.equal(solve(p).ok,true);p=JSON.parse(JSON.stringify(p));assert.throws(()=>send(p,{kind:'answer',answer:p.session.q.answer,durationMs:1}),/Already/);send(p,{kind:'next'});}assert.equal(p.session.phase,'complete');assert.equal(p.session.score,800);assert.equal(p.games[game.id].played,1);assert.equal(p.games[game.id].level,['builder','orbit','flashcards'].includes(game.id)?2:3);assert.equal(Object.keys(p.games).length,1);assert.throws(()=>send(p,{kind:'next'}));assert.equal(p.xp,['wordoku','cipher'].includes(game.id)?0:96);
});
test('Wrong answers retain a question, restore help after two errors, and lower future difficulty',()=>{const p=fresh('explorer');send(p,{kind:'start',game:'rhyme',level:3});const id=p.session.q.id;send(p,{kind:'answer',answer:'!',durationMs:100});send(p,{kind:'answer',answer:'!',durationMs:100});assert.equal(p.session.q.id,id);assert.equal(p.session.q.level,3);assert.equal(p.session.level,1);assert.equal(p.session.help,true);assert.equal(solve(p).independent,false);assert.equal(p.xp,6);send(p,{kind:'next'});assert.equal(p.session.q.level,1);});
test('Help survives refresh and cannot be erased by clearing drafts',()=>{let p=fresh('beginner');send(p,{kind:'start',game:'builder'});send(p,{kind:'help'});send(p,{kind:'draft',draft:[]});p=JSON.parse(JSON.stringify(p));assert.equal(solve(p).independent,false);assert.equal(p.session.score,40);});
test('Content has a valid answer, unique choices, legal transformations and complete finite audio',()=>{const voice=new Set(voiceLines());for(const g of GAMES)for(let level=1;level<=3;level++)for(let n=0;n<144;n++){const q=question(g.id,level,n);if(q.prompt)assert.ok(voice.has(q.prompt),q.prompt);if(q.help)assert.ok(voice.has(q.help),q.help);assert.equal(new Set(q.options).size,q.options.length);if(q.options.length)assert.ok(q.options.includes(q.answer));if(g.id==='transform')assert.equal([...q.from].filter((c,i)=>c!==q.word[i]).length,1);if(g.id==='cipher')assert.equal(q.code.map(c=>q.key[c]).join(''),q.word);if(g.id==='search')assert.equal(q.path.map(i=>q.grid[i]).join(''),q.word);}});
test('Reject illegal drafts, duplicate carriages, stale revisions and other players',()=>{const p=fresh('admin');assert.throws(()=>fresh('../explorer'));send(p,{kind:'start',game:'train'});assert.throws(()=>act(p,{kind:'help',revision:0,questionId:p.session.q.id}));assert.throws(()=>send(p,{kind:'draft',draft:['<script>']}));assert.throws(()=>send(p,{kind:'draft',draft:[p.session.q.tiles[0],p.session.q.tiles[0]]}));assert.throws(()=>send(p,{kind:'answer',answer:'x',durationMs:Infinity}));const f=fresh('explorer');solve(p);assert.equal(f.xp,0);});
test('Painting is separate saved creative play; no invented mastery or XP',()=>{let p=fresh('beginner');send(p,{kind:'start',game:'pixel'});const pixels=Array(64).fill(2);send(p,{kind:'art',pixels});p=JSON.parse(JSON.stringify(p));assert.deepEqual(p.art,pixels);assert.equal(p.xp,0);assert.throws(()=>send(p,{kind:'art',pixels:Array(64).fill(8)}));send(p,{kind:'start',game:'blaster'});assert.deepEqual(p.art,pixels);});
test('Wordoku cannot replace givens and radar accepts only an adjacent straight path',()=>{const p=fresh('admin');send(p,{kind:'start',game:'wordoku'});assert.throws(()=>send(p,{kind:'draft',draft:Array(16).fill('')}));send(p,{kind:'start',game:'search'});send(p,{kind:'draft',draft:p.session.q.path.map(String).reverse()});assert.equal(send(p,{kind:'answer',answer:'',durationMs:3}).ok,false);});
