import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,readFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {spawn} from 'node:child_process';
import {once} from 'node:events';
import {numberPaths} from '../lib/number-trace.mjs';
import {PARTS} from '../lib/art.mjs';
test('private API saves, reloads, isolates players and rejects replays and foreign origins',async()=>{
 const data=await mkdtemp(join(tmpdir(),'number-park-http-')),child=spawn(process.execPath,['server.mjs'],{cwd:new URL('..',import.meta.url),env:{...process.env,NUMBER_PARK_DATA:data,HOST:'127.0.0.1',PORT:'14323'},stdio:['ignore','pipe','pipe']});
 const timeout=setTimeout(()=>child.kill(),10000);
 try{
  await Promise.race([once(child.stdout,'data'),once(child,'exit').then(()=>{throw Error('Server stopped early');})]);
  const base='http://127.0.0.1:14323',post=(input,headers={})=>fetch(base+'/api/admin/action',{method:'POST',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify(input)});
  let p=await(await fetch(base+'/api/admin')).json();assert.equal(p.xp,0);
  const start={kind:'start',game:'mix',revision:0};assert.equal((await post(start,{Origin:'https://evil.example'})).status,403);
  p=await(await post(start)).json();assert.equal(p.session.question.answer,undefined);
  const q=p.session.question,answer=q.total;
  const input={kind:'answer',questionId:q.id,answer,revision:p.revision};const responses=await Promise.all([post(input),post(input)]);assert.deepEqual(responses.map(r=>r.status).sort(),[200,409]);
  p=await(await fetch(base+'/api/admin')).json();assert.equal(p.xp,10);assert.equal(JSON.parse(await readFile(join(data,'admin.json'))).xp,10);
  assert.equal((await(await fetch(base+'/api/beginner')).json()).xp,0);assert.equal((await(await fetch(base+'/api/explorer')).json()).xp,0);
  assert.equal((await post({kind:'drawing',revision:p.revision,strokes:[[[0,0],[100,100]]]})).status,200);
  p=await(await fetch(base+'/api/admin')).json();assert.equal(p.drawing.length,1);
  p=await(await post({kind:'trace',digit:'10',strokes:numberPaths(10),revision:p.revision})).json();
  assert.equal(p.traceNext,'11');assert.equal(p.guided['10'],1);
  assert.equal(JSON.parse(await readFile(join(data,'admin.json'))).traceNext,'11');
  assert.equal((await(await fetch(base+'/api/admin')).json()).traceNext,'11');
  for(const route of ['/server.mjs','/logs','/reference','/voice/../admin.json','/data/doodle-model.json','/data/symbol-model.json'])assert.equal((await fetch(base+route)).status,404);
  assert.equal((await fetch(base+'/icons/number-park-192.png')).headers.get('content-type'),'image/png');
  assert.equal((await fetch(base+'/')).status,200);
  const event=await fetch(base+'/api/admin/events',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:'pattern',name:'placed',detail:JSON.stringify({questionId:'fixture',method:'drag',piece:'🐶'})})});
  assert.equal(event.status,200);
  p=await(await post({kind:'reading_start',revision:p.revision})).json();assert.equal(p.reading.session.questions[0].kind,'sounds');assert.equal(p.traceNext,'11');assert.equal(p.session.game,'mix');
  assert.equal((await fetch(base+'/api/admin/events',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:'reading',name:'voice',detail:'fixture'})})).status,200);
  p=await(await post({kind:'art_guess',revision:p.revision,strokes:[PARTS.triangle.path],label:'house'})).json();assert.equal(p.art.lastGuess.label,'triangle');assert.equal(p.xp,10);
  p=await(await post({kind:'art_label',revision:p.revision,guessId:p.art.lastGuess.id,label:'tree'})).json();assert.equal(p.art.lastGuess.childLabel,'tree');
  p=await(await post({kind:'art_start',revision:p.revision})).json();
  p=await(await post({kind:'art_part',revision:p.revision,missionId:p.art.mission.id,part:0,strokes:[PARTS.circle.path]})).json();assert.equal(p.art.mission.part,1);
  const restored=await(await fetch(base+'/api/admin')).json();assert.equal(restored.art.mission.part,1);assert.equal(restored.art.lastGuess.childLabel,'tree');assert.equal(restored.reading.session.questions[0].kind,'sounds');assert.deepEqual(restored.drawing,[[[0,0],[100,100]]]);
  assert.equal((await(await fetch(base+'/api/beginner')).json()).art,undefined);
  const glyphs=JSON.parse(await readFile(new URL('../data/symbol-model.json',import.meta.url))).glyphs;
  p=await(await post({kind:'art_guess',revision:p.revision,strokes:glyphs.R})).json();assert.equal(p.art.lastGuess.label,'R');
  p=await(await post({kind:'art_label',revision:p.revision,guessId:p.art.lastGuess.id,label:'r'})).json();assert.equal(p.art.lastGuess.childLabel,'r');
  p=await(await post({kind:'art_guess',revision:p.revision,strokes:numberPaths(13),mode:'numbers'})).json();assert.equal(p.art.lastGuess.label,'13');
  assert.equal((await(await fetch(base+'/api/admin')).json()).art.lastGuess.label,'13');assert.equal(p.xp,10);assert.equal(p.art.mission.part,1);
  assert.equal((await post({kind:'art_guess',revision:p.revision,strokes:glyphs.R,mode:'invalid'})).status,400);
  const lines=(await readFile(join(data,'logs',new Date().toISOString().slice(0,10)+'.jsonl'),'utf8')).trim().split('\n').map(JSON.parse);
  assert.ok(lines.some(r=>r.type==='action'&&r.input.kind==='art_guess'&&r.art.label==='triangle'));
  assert.ok(lines.some(r=>r.type==='client'&&r.kind==='pattern'&&r.name==='placed'&&JSON.parse(r.detail).method==='drag'));
  assert.ok(lines.some(r=>r.type==='action'&&r.input.kind==='reading_start'&&r.reading.question.kind==='sounds'));
  const stale=await post(input,{'X-Game-Client':'test-screen-2','X-Game-Request':'test-request'});assert.equal(stale.status,409);
  await fetch(base+'/api/admin',{headers:{'X-Game-Client':'test-screen-2','X-Game-Request':'test-read'}});
  const diagnostics=(await readFile(join(data,'logs',new Date().toISOString().slice(0,10)+'.jsonl'),'utf8')).trim().split('\n').map(JSON.parse);
  const rejected=diagnostics.find(r=>r.type==='rejected'&&r.requestId==='test-request');assert.equal(rejected.clientId,'test-screen-2');assert.equal(rejected.submittedRevision,input.revision);assert.equal(rejected.currentRevision,p.revision);assert.equal(rejected.questionId,q.id);
  assert.ok(diagnostics.some(r=>r.type==='sync_read'&&r.requestId==='test-read'&&r.revision===p.revision));
 }finally{clearTimeout(timeout);child.kill();}
});
