'use client';
import {useEffect,useRef,useState} from 'react';
import {orbitPosition,dockAt,clamp,raceDistance,raceRival} from '../lib/flight.mjs';
function useClock(running,key){const [time,setTime]=useState(0);useEffect(()=>setTime(0),[key]);useEffect(()=>{if(!running)return;let last=performance.now();const t=setInterval(()=>{const now=performance.now();setTime(s=>s+Math.min(.1,(now-last)/1000));last=now;},50);return()=>clearInterval(t);},[running]);return time;}
export function OrbitBuilder({session,active,paused,onDraft,onCommit,onLetter}){
 const q=session.q,time=useClock(active&&!paused,session.run),[selected,setSelected]=useState([]),[launch,setLaunch]=useState(false),guard=useRef(false);
 useEffect(()=>{const used=[];for(const c of session.draft){const i=q.nodes.findIndex((v,i)=>v===c&&!used.includes(i));if(i>=0)used.push(i);}setSelected(used);setLaunch(false);},[q.id]);
 const positions=q.nodes.map((_,i)=>orbitPosition(i,q.nodes.length,time*(session.mode==="arcade"?1.7:1))),points=[{x:10,y:83},...selected.map(i=>positions[i])],last=points.at(-1);
 async function pick(i){if(!active||guard.current||selected.includes(i)||selected.length>=q.word.length)return;guard.current=true;const next=[...selected,i];setSelected(next);onLetter(q.nodes[i]);const d=next.map(j=>q.nodes[j]);const ok=await onDraft(d);if(ok&&d.length===q.word.length){setLaunch(true);await onCommit();}if(!ok)setSelected(selected);guard.current=false;}
 return <div className="orbit-game"><div className="mission-target"><small>CONNECT THE LETTERS · BUILD THE WORD</small><strong>{session.help?q.word.toUpperCase():session.draft.map(c=>c.toUpperCase()).join(' ')+' _'.repeat(Math.max(0,q.word.length-session.draft.length))}</strong></div><div className={'orbit-world '+(launch?'launching':'')}><div className="flight-stars"/><svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><polyline points={points.map(p=>p.x+','+p.y).join(' ')} fill="none" stroke="#ffcf62" strokeWidth=".6" strokeDasharray="1.2 .8"/></svg>{q.nodes.map((c,i)=><button key={i} className={'orbit-node '+(selected.includes(i)?'linked':'')} style={{left:positions[i].x+'%',top:positions[i].y+'%'}} disabled={!active||selected.includes(i)} onClick={()=>pick(i)} aria-label={`Connect ${c.toUpperCase()}, asteroid ${i+1}`}>{c.toUpperCase()}</button>)}<img className="orbit-pilot" src="/assets/ship-dynamic-v1.png" alt="Your ship follows the linked letters" style={{left:last.x+'%',top:last.y+'%'}}/></div><div className="arcade-inputs"><button disabled={!active} onClick={async()=>{if(await onDraft([])){setSelected([]);setLaunch(false);}}}>↶ Clear route</button><small>Tap the drifting letters in order. Your ship follows your route.</small></div></div>;
}
export function CargoSorter({session,active,paused,onAnswer,onEvent}){
 const q=session.q,time=useClock(active&&!paused,q.id),ref=useRef(null),drag=useRef(null),[position,setPosition]=useState(null),[drop,setDrop]=useState(null),pending=useRef(false);
 useEffect(()=>{setPosition(null);setDrop(null);pending.current=false;},[q.id]);
 const x=position?.x??50+Math.sin(time*(session.mode==="arcade"?1.4:.7))*20,y=position?.y??40+Math.sin(time*.8)*4;
 async function deliver(index){if(!active||pending.current)return;pending.current=true;setPosition({x:(index+.5)/q.options.length*100,y:80});setDrop(index);onEvent('cargo_drop',q.options[index]);const result=await onAnswer(q.options[index]);if(!result?.result?.ok){setPosition(null);setDrop(null);}pending.current=false;}
 function move(e){const b=ref.current.getBoundingClientRect();setPosition({x:clamp((e.clientX-b.left)/b.width*100,8,92),y:clamp((e.clientY-b.top)/b.height*100,12,88)});}
 return <div className="sort-game"><div className="mission-target"><small>SORT THE WORD · MATCH ITS ENDING</small><strong>{q.word.toUpperCase()}</strong></div><div className="sort-world" ref={ref} onPointerMove={e=>{if(drag.current===e.pointerId&&active)move(e);}} onPointerUp={e=>{if(drag.current!==e.pointerId)return;drag.current=null;if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);const b=ref.current.getBoundingClientRect(),py=(e.clientY-b.top)/b.height;if(py>.67)void deliver(dockAt((e.clientX-b.left)/b.width*100,q.options.length));else setPosition(null);}} onPointerCancel={()=>{drag.current=null;setPosition(null);}}>
 <div className="sort-guides"/><button className={'word-cluster '+(drop!==null?'docking':'')} disabled={!active} style={{left:x+'%',top:y+'%'}} aria-label={`Drag ${q.word.toUpperCase()} to an ending dock`} onPointerDown={e=>{if(!active||e.button!==0)return;drag.current=e.pointerId;ref.current.setPointerCapture(e.pointerId);move(e);e.preventDefault();}}>{[...q.word].map((c,i)=><span key={i} style={{'--bubble':i}}>{c.toUpperCase()}</span>)}</button>
 <div className="cargo-docks">{q.options.map((ending,i)=><button key={ending} style={{'--dock-color':['#6bb8ff','#b78cff','#ffb876','#77ecc4'][i]}} className={(session.help&&ending===q.answer?'hint-glow ':'')+(drop===i?'received':'')} disabled={!active} onClick={()=>deliver(i)}><small>DOCK {i+1}</small><strong>–{ending.toUpperCase()}</strong><span>Drop here</span></button>)}</div></div><p className="activity-tip">Drag the whole word into its dock—or tap the dock.</p></div>;
}
export function FlashcardRally({session,active,paused,onDraft,onCommit,onAnswer,onLetter,onHear}){
 const q=session.q,elapsed=useClock(active&&!paused,q.id+':'+session.misses),race=session.mode==='arcade',progress=raceDistance(session.results),rival=race?raceRival((session.activeMs||0)/1000+(session.phase==="question"?elapsed:0),120):Math.max(0,progress-12),spelling=session.deck==='spelling';
 const [typed,setTyped]=useState('');const guard=useRef(false);
 useEffect(()=>{setTyped(session.draft.join(''));guard.current=false;},[q.id]);
 async function type(c){if(!active||guard.current)return;onLetter(c);if(!spelling){void onAnswer(c);return;}if(typed.length>=q.word.length)return;guard.current=true;const next=typed+c;setTyped(next);if(await onDraft([...next])){if(next.length===q.word.length)await onCommit();}else setTyped(typed);guard.current=false;}
 return <div className="rally"><div className="rally-track" aria-label={`Race progress ${Math.round(progress)} percent`}><div className="race-fill" style={{width:progress+'%'}}/><span className="rally-racer" style={{left:`${Math.min(91,progress*.91)}%`}}><img src="/assets/ship-dynamic-v1.png" alt="Your ship"/></span>{race&&<span className="rally-rival" style={{left:`${Math.min(91,rival*.91)}%`}} aria-label="Computer pace ship">🚀</span>}<span className="finish-flag">⚑</span></div><div className="race-caption"><span>{race?'You vs. Comet · beat its pace':'Practice · your own pace'}</span><span>{session.results.length} / 8 cards</span></div>
 <div className="flashcard-layout"><div className={'card-stack '+(session.phase==='result'?'card-correct':'')} key={q.id}><div className="flashcard"><small>{session.deck==='letters'?'BIG → little':spelling?'LISTEN & SPELL':'FIND THE MISSING LETTER'}</small><strong>{q.upperCue||q.display||typed.toUpperCase()||'♪'}</strong>{spelling&&<div className="card-slots">{[...q.word].map((_,i)=><span key={i}>{typed[i]?.toUpperCase()||'·'}</span>)}</div>}{session.help&&<p className="card-hint">{spelling?q.word.toUpperCase():session.deck==='letters'?q.answer:q.answer.toUpperCase()}</p>}<button className="card-hear" onClick={onHear} aria-label="Hear flashcard">🔊</button>{session.phase==='result'&&<div className="card-stamp">✓</div>}</div></div>
 <div className="card-keypad">{q.tiles.map(c=><button key={c} disabled={!active} onClick={()=>type(c)}>{session.deck==='letters'?c:c.toUpperCase()}</button>)}{spelling&&<button className="key-erase" disabled={!active} onClick={async()=>{const next=typed.slice(0,-1);if(await onDraft([...next]))setTyped(next);}}>⌫</button>}</div></div><p className="activity-tip">{race?'Correct cards move your ship. Helped cards are practice, not unaided wins.':'The next card arrives automatically. No timer and no lost lives.'}</p></div>;
}
