'use client';
import {useEffect,useRef,useState} from 'react';
import Flight from './Flight';
import {OrbitBuilder,CargoSorter,FlashcardRally} from './ArcadeActivities';
import {Lobby,Brief} from './Lobby';
import './dynamic.css';
import './player-banner.css';
import {GAMES,LINES,INSTRUCTIONS} from '../lib/engine.mjs';
import {editBuilderDraft} from '../lib/builder.mjs';
import {CoachVoice} from '../lib/voice.mjs';
import {ArcadeAudio,TRACKS,LASERS,audioPreferences} from '../lib/arcade-audio.mjs';
import {shortPrompt,needsWordClue,shouldAnnounce} from '../lib/speech-plan.mjs';
import {foundationState} from '../lib/foundation.mjs';
import {LOWERCASE_STAGES,lowerState,lowerReady} from '../lib/lowercase.mjs';
const flying=id=>['blaster','lowercase'].includes(id);
import {nearestTarget,aimFromClient,releaseAim,movedPointer} from '../lib/aim.mjs';
const COLORS=['#10243c','#61e4ee','#fbcd62','#f28dd1','#9c92ff','#71e5ba','#f6f6ff','#ff785f'];
function displayInstruction(q){if(!q)return '';if(q.game==='rhyme')return shortPrompt(q);if(q.focus==='lowercase')return q.upperCue?'Find the little partner for this big letter.':'Listen. Find the little letter.';return ({blaster:'Listen to the word. Blast the missing letter.',builder:'Listen to the word. Build it with your letter tiles.',orbit:'Hear the word. Connect its letters in order.',flashcards:q.deck==='letters'?'Match the big letter to its little partner.':'Hear the word. Build your answer on the card.',transform:'Listen to the new word. Select a letter to replace.',train:'Listen to the sentence. Put the carriages in order.',beats:'Listen to the word. Tap once for each syllable.'})[q.game]||q.prompt;}
function Ship({mini=false,x,interactive=false,disabled=false,onFire}){const Tag=interactive?'button':'div';return <Tag type={interactive?'button':undefined} className={'ship '+(mini?'mini':'')+(interactive?' ship-trigger':'')} style={x===undefined?undefined:{left:`calc(${x}% - 37px)`}} aria-hidden={interactive?undefined:true} aria-label={interactive?'Fire spaceship':undefined} disabled={interactive?disabled:undefined} onClick={interactive?e=>{if(e.detail===0)onFire();}:undefined}><i className="fin left"/><i className="hull"/><i className="window"/><i className="fin right"/><i className="flame"/></Tag>;}
function Cover({game}){const id=game.id;return <div className={'cover '+id} aria-hidden="true">{['lowercase','blaster','asteroids','rhyme'].includes(id)?<><span className="orb o1">{id==='rhyme'?'cat':'a'}</span><span className="orb o2">{id==='rhyme'?'hat':'m'}</span><span className="orb o3">{id==='asteroids'?'🐈':'s'}</span><Ship mini/></>:id==='wordoku'?<div className="mini-grid">{'mas tamas'.replaceAll(' ','').split('').slice(0,8).map((x,i)=><i key={i}>{i%3?x:'?'}</i>)}</div>:id==='sort'?<><span className="cargo">cat</span><div className="dock-mini"><i>–at</i><i>–og</i></div></>:id==='beats'?<><span className="big-icon">🥁</span><div className="beat-dots">● ● ●</div></>:id==='pixel'?<div className="pixel-mini">{Array.from({length:25},(_,i)=><i key={i} style={{background:[2,6,8,10,11,12,13,14,15,19,20,24].includes(i)?game.color:'transparent'}}/>)}</div>:id==='cipher'?<><div className="code-mini">◆ ● ▲</div><div className="tile-mini">c a t</div></>:id==='train'?<><span className="big-icon">🚂</span><div className="tile-mini">The cat naps.</div></>:id==='search'?<div className="radar-mini"><span>c a t</span><span>m s p</span><span>e n r</span></div>:<><div className="tile-mini">{id==='transform'?'cat → hat':'c  a  t'}</div><span className="big-icon">{id==='transform'?'✦':'🚀'}</span></>}</div>;}
export default function Arcade(){
 const [p,setP]=useState(null),[id,setId]=useState('explorer'),[screen,setScreen]=useState('gallery'),[selected,setSelected]=useState(null),[level,setLevel]=useState(1),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[sound,setSound]=useState(true),[speaking,setSpeaking]=useState(false),[paused,setPaused]=useState(false),[filter,setFilter]=useState('foundation'),[practiceFocus,setPracticeFocus]=useState('words'),[cursor,setCursor]=useState(0),[color,setColor]=useState(1),[shot,setShot]=useState(null),[tutorial,setTutorial]=useState(false);
 const [shipX,setShipX]=useState(50),[mode,setMode]=useState('practice'),[deck,setDeck]=useState('words'),[countdown,setCountdown]=useState(0);
 const [audioPrefs,setAudioPrefs]=useState(()=>audioPreferences()),[audioNotice,setAudioNotice]=useState('');
 const audio=useRef(null),wordEdits=useRef([]);
 const current=useRef(null),lock=useRef(false),voice=useRef(null),arena=useRef(null),gesture=useRef(null),started=useRef(Date.now()),soundRef=useRef(true),shotTimer=useRef(null);
 const activeTime=useRef(0);
 const session=p?.session,q=session?.q,game=GAMES.find(g=>g.id===session?.game);
 useEffect(()=>{if(q&&game?.id==='wordoku')setCursor(q.grid.findIndex(x=>!x));},[q?.id]);
 async function event(kind,name='',detail=''){try{await fetch(`/api/${current.current?.id||id}/events`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({events:[{kind,name,detail,game:current.current?.session?.game}]})});}catch{}}
 function stop(){voice.current?.stop();setSpeaking(false);}
 function say(text,force=false){if(q?.game==='rhyme'&&text===q.prompt)text=shortPrompt(q);if(text&&(soundRef.current||force))return voice.current?.speak(text);}
 function announce(profile,first=false){const next=profile.session?.q;if(!shouldAnnounce(next,soundRef.current))return;void event('voice','prompt_requested',JSON.stringify({text:shortPrompt(next),questionId:next.id,chatEnabled:soundRef.current}));voice.current?.instruction(shortPrompt(next),{key:next.game,essential:first||needsWordClue(next)});}

 function effect(ok){audio.current?.feedback(ok);}
 function changeAudio(update){const next=audioPreferences({...audioPrefs,...update});setAudioPrefs(next);audio.current?.configure(next);void audio.current?.unlock();try{localStorage.setItem(`word-arcade-audio-v1:${id}`,JSON.stringify(next));}catch{void event('audio','preferences_unavailable');}void event('audio','settings',JSON.stringify(next));}
 useEffect(()=>{audio.current=new ArcadeAudio({record:(name,detail)=>void event('audio',name,JSON.stringify(detail)),notify:setAudioNotice});return()=>audio.current?.dispose();},[]);
 useEffect(()=>{let next=audioPreferences();try{next=audioPreferences(JSON.parse(localStorage.getItem(`word-arcade-audio-v1:${id}`)));}catch{}setAudioPrefs(next);audio.current?.configure(next);},[id]);
 useEffect(()=>{audio.current?.setPaused(paused||tutorial);},[paused,tutorial]);
 useEffect(()=>{audio.current?.duck(speaking);},[speaking]);
 async function load(player){stop();setMessage('');setP(null);setId(player);current.current=null;try{const r=await fetch(`/api/${player}`),d=await r.json();if(!r.ok)throw Error(d.error);setP(d.profile);current.current=d.profile;void event('open','arcade',`${innerWidth}×${innerHeight}`);}catch(e){setMessage(e.message);}}
 useEffect(()=>{voice.current=new CoachVoice(setMessage,(kind,detail)=>void event('voice',kind,JSON.stringify(detail)));const playerAudio=voice.current.player;playerAudio.addEventListener('playing',()=>setSpeaking(true));for(const name of ['pause','ended','emptied','error'])playerAudio.addEventListener(name,()=>setSpeaking(false));const player=new URLSearchParams(location.search).get('player');void load(['explorer','beginner','admin'].includes(player)?player:'explorer');const onError=e=>void event('error','javascript',e.message||'Unhandled error');const onVisibility=()=>{if(document.hidden){stop();setPaused(true);}void event('visibility',document.visibilityState);};window.addEventListener('error',onError);document.addEventListener('visibilitychange',onVisibility);return()=>{stop();playerAudio.remove();clearTimeout(shotTimer.current);window.removeEventListener('error',onError);document.removeEventListener('visibilitychange',onVisibility);};},[]);
 async function action(input){if(lock.current||!current.current)return null;lock.current=true;setBusy(true);if(['start','next','help'].includes(input.kind)||input.kind==='answer'&&voice.current?.mode!=='letter')stop();try{const old=current.current;const r=await fetch(`/api/${old.id}/action`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...input,questionId:old.session?.q?.id,revision:old.revision})}),d=await r.json();if(!r.ok){if(d.profile){current.current=d.profile;setP(d.profile);}throw Error(d.error);}current.current=d.profile;setP(d.profile);setMessage(d.result.line||'');if(['start','next'].includes(input.kind)){started.current=Date.now();setCursor(d.profile.session.game==='wordoku'?d.profile.session.q?.grid.findIndex(x=>!x)||0:0);}if(['start','next'].includes(input.kind)&&d.profile.session?.phase==='question')announce(d.profile,input.kind==='start');else if(input.kind==='answer'&&old.session.game==='builder'&&d.result.ok)void say(`Yes! ${old.session.q.word}.`,true);else if(input.kind==='help')void say(d.result.line,needsWordClue(d.profile.session?.q));else if(d.result.line&&soundRef.current)void voice.current?.feedback(d.result.ok!==false);if(input.kind==='answer')activeTime.current=0;void event('button',input.kind);return d;}catch(e){setMessage(e.message);void event('error','request',e.message);return null;}finally{lock.current=false;setBusy(false);flushWordEdits();}}
 async function launch(){stop();const d=await action({kind:'start',game:selected.id,level,focus:practiceFocus,mode,deck});if(d){setScreen('game');setPaused(false);setTutorial(false);setCountdown(3);}}
 function choose(g,nextDeck='words'){stop();setSelected(g);setPracticeFocus('words');setDeck(nextDeck);setLevel(p.games[g.id]?.level||1);setScreen('brief');setMessage('');setPaused(false);setCountdown(0);}
 function refreshGame(){if(lock.current){setMessage('Finishing your save. Try Refresh again in a moment.');return;}stop();audio.current?.setPaused(true);window.location.reload();}
 function home(){if(busy)return;stop();setScreen('gallery');setPaused(false);setMessage('');clearTimeout(shotTimer.current);setShot(null);}
 async function answer(value){if(lock.current||!active)return;const isShot=flying(game.id)&&q.options.includes(value);if(isShot){const centers=targetCenters();setShipX(centers[q.options.indexOf(value)]??shipX);audio.current?.laser();setShot({value,ok:true,key:Date.now(),pending:true});clearTimeout(shotTimer.current);shotTimer.current=setTimeout(()=>setShot(null),650);}const d=await action({kind:'answer',answer:value,durationMs:Math.min(86400000,Math.round(activeTime.current))});if(d){if(isShot)setShot(previous=>previous?{...previous,ok:d.result.ok,pending:false}:null);else{effect(d.result.ok);setShot({value,ok:d.result.ok,key:Date.now()});clearTimeout(shotTimer.current);shotTimer.current=setTimeout(()=>setShot(null),650);}}}
 async function draft(d){await action({kind:'draft',draft:d});}
 function editBuilder(operation,index){
  if(!current.current?.session||paused||tutorial||countdown)return;
  wordEdits.current.push({operation,index,questionId:current.current.session.q.id});
  flushWordEdits();
 }
 function flushWordEdits(){
  if(lock.current)return;
  while(wordEdits.current.length){
   const edit=wordEdits.current.shift(),s=current.current?.session;
   if(s?.game!=='builder'||s.phase!=='question'||s.q.id!==edit.questionId)continue;
   const next=editBuilderDraft(s.draft,edit.operation,edit.index);
   void action({kind:'draft',draft:next}).then(d=>{if(d)void event('button','builder_edit',JSON.stringify(edit));});
   return;
  }
 }
 async function tile(t){if(lock.current||!active)return;if(game.id!=='train'&&(soundRef.current||game.id==='builder'))void voice.current?.letter(`Letter ${t.toUpperCase()}.`);if(['wordoku','transform'].includes(game.id)){const d=[...session.draft];d[cursor]=t;await draft(d);}else if(game.id==='builder'&&session.draft.includes('')||session.draft.length<(game.id==='train'?q.tiles.length:q.word.length)){const next=[...session.draft],hole=game.id==='builder'?next.indexOf(''):-1;if(hole>=0)next[hole]=t;else next.push(t);const saved=await action({kind:'draft',draft:next});if(saved&&game.id==='builder'&&next.length===q.word.length&&next.every(Boolean)){await commitDynamic();}}}
 const helped=session?.help||session?.misses>0,active=session?.phase==='question'&&!busy&&!paused&&!tutorial&&!countdown;
 useEffect(()=>{activeTime.current=0;},[q?.id]);
 useEffect(()=>{if(!active||screen!=='game')return;let last=performance.now();const timer=setInterval(()=>{const now=performance.now();activeTime.current+=Math.min(250,now-last);last=now;},50);return()=>clearInterval(timer);},[active,screen]);
 useEffect(()=>{if(!countdown||paused||tutorial||screen!=='game')return;const t=setTimeout(()=>{setCountdown(n=>n-1);audio.current?.feedback(true);},650);return()=>clearTimeout(t);},[countdown,paused,tutorial,screen]);
 useEffect(()=>{if(screen!=='game'||session?.phase!=='result'||paused||tutorial||busy)return;let ticks=0;const timer=setInterval(()=>{ticks++;if((!speaking&&ticks>=6)||ticks>=15){clearInterval(timer);void action({kind:'next'});}},180);return()=>clearInterval(timer);},[session?.q?.id,session?.phase,paused,tutorial,busy,screen,speaking]);
 async function commitDynamic(){const d=await action({kind:'answer',durationMs:Math.min(86400000,Math.round(activeTime.current))});if(d)effect(d.result.ok);return d;}
 async function dynamicAnswer(value){const d=await action({kind:'answer',answer:value,durationMs:Math.min(86400000,Math.round(activeTime.current))});if(d)effect(d.result.ok);return d;}
 const dynamicDraft=async d=>!!(await action({kind:'draft',draft:d}));
 const readLetter=c=>void voice.current?.letter(`Letter ${c.toUpperCase()}.`);
 function targetCenters(){const el=arena.current;if(!el)return [];const box=el.getBoundingClientRect();return [...el.querySelectorAll('.target')].map(t=>{const r=t.getBoundingClientRect();return (r.left+r.width/2-box.left)/box.width*100;});}
 function fire(){if(!active||lock.current)return;const centers=targetCenters(),index=nearestTarget(shipX,centers);if(index!==null){setShipX(centers[index]);void event('button','ship_fire');void answer(q.options[index]);}}
 function steer(direction){const centers=targetCenters(),index=nearestTarget(shipX,centers);if(index!==null)setShipX(centers[Math.max(0,Math.min(centers.length-1,index+direction))]);}
 function beginAim(e){if(!active||e.button!==0||!e.isPrimary||gesture.current)return;const shipTap=!!e.target.closest('.ship-trigger');if(e.target.closest('.target'))return;const r=e.currentTarget.getBoundingClientRect();gesture.current={id:e.pointerId,x:e.clientX,y:e.clientY,shipTap,moved:false,aim:shipX,offset:shipTap?e.clientX-(r.left+shipX*r.width/100):0};e.currentTarget.setPointerCapture(e.pointerId);if(!shipTap){const x=aimFromClient(e.clientX,r.left,r.width);gesture.current.aim=x;setShipX(x);}e.preventDefault();}
 function moveAim(e){const g=gesture.current;if(!g||g.id!==e.pointerId||!active)return;g.moved ||= movedPointer(g,e.clientX,e.clientY);if(!g.moved)return;const r=e.currentTarget.getBoundingClientRect();g.aim=aimFromClient(e.clientX-g.offset,r.left,r.width);setShipX(g.aim);}
 function endAim(e,canceled=false){const g=gesture.current;if(!g||g.id!==e.pointerId)return;g.moved ||= movedPointer(g,e.clientX,e.clientY);const centers=targetCenters(),result=releaseAim(g,g.aim,centers,canceled);gesture.current=null;if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);setShipX(result.x);void event('button',canceled?'aim_cancel':'aim_snap',String(result.index));if(result.fire&&active&&result.index!==null)void answer(q.options[result.index]);}
 useEffect(()=>{gesture.current=null;if(flying(game?.id)){const centers=targetCenters();setShipX(x=>{const index=nearestTarget(x,centers);return index===null?x:centers[index];});}},[q?.id,screen,paused,tutorial]);
 useEffect(()=>{const el=arena.current;if(!el)return;const observer=new ResizeObserver(()=>{if(gesture.current)return;const centers=targetCenters();setShipX(x=>{const i=nearestTarget(x,centers);return i===null?x:centers[i];});});observer.observe(el);return()=>observer.disconnect();},[screen,game?.id]);
 useEffect(()=>{if(screen!=='game'||!flying(game?.id)||!active)return;const key=e=>{if(e.target.closest('input,select,textarea,summary,.audio-menu'))return;if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();steer(e.key==='ArrowLeft'?-1:1);}if(e.code==='Space'&&e.target.tagName!=='BUTTON'){e.preventDefault();fire();}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[screen,game?.id,active,q,shipX]);
 const mark=x=>session?.help&&(x===q?.answer||q?.path?.includes(Number(x)))?'helped':'';
 function choices(values,render){return <div className={'answer-options '+(flying(game.id)?'blaster':game.id)}>{values.map((v,i)=><button key={v} className={'target '+mark(v)+(shot?.value===v&&!shot.pending?(shot.ok?' hit':' wobble'):'')} style={{'--i':i,fontFamily:q?.font||'inherit'}} disabled={!active} onClick={()=>answer(v)} aria-label={game.id==='asteroids'?`Picture ${v}`:v}>{render?render(v):q.printCase==='upper'?v.toUpperCase():v}</button>)}</div>;}
 function puzzle(){
  if(game.id==='orbit')return <OrbitBuilder key={session.run} session={session} active={active} paused={paused||tutorial} onDraft={dynamicDraft} onCommit={commitDynamic} onLetter={readLetter}/>;
  if(game.id==='sort')return <CargoSorter session={session} active={active} paused={paused||tutorial} onAnswer={dynamicAnswer} onEvent={(name,detail)=>void event('gameplay',name,detail)}/>;
  if(game.id==='flashcards')return <FlashcardRally key={session.run} session={session} active={active} paused={paused||tutorial} onDraft={dynamicDraft} onCommit={commitDynamic} onAnswer={dynamicAnswer} onLetter={readLetter} onHear={()=>say(shortPrompt(q),true)}/>;
  if(['blaster','asteroids','rhyme'].includes(game.id))return <Flight key={q.id} q={q} active={active} paused={paused||tutorial} mode={session.mode||'practice'} helped={helped} onAnswer={async value=>{const d=await action({kind:'answer',answer:value,durationMs:Math.min(86400000,Math.round(activeTime.current))});if(d)effect(d.result.ok);return d;}} onHear={value=>{void say(`The word is ${value}.`,true);void event('voice','rhyme_choice',value);}} onShot={()=>audio.current?.laser()} onEvent={(name,detail)=>void event('button',name,detail)}/>;
  if(game.id==='pixel')return <><div className="palette">{COLORS.map((c,i)=><button key={c} onClick={()=>setColor(i)} className={color===i?'selected':''} style={{background:c}} aria-label={i===0?'Eraser':`Color ${i}`}/>)}</div><div className="paint-grid">{p.art.map((c,i)=><button key={i} aria-label={`Pixel ${i+1}`} style={{background:COLORS[c]}} disabled={busy||paused} onClick={()=>{const pixels=[...p.art];pixels[i]=color;void action({kind:'art',pixels});}}/>)}</div><p className="quiet">Every pixel is saved. Creative play · no correctness score.</p></>;
  if(flying(game.id))return <><div className="word-signal"><small>{q?.foundation?`WORD FAMILY ${q.stage} · THREE-LETTER WORDS`:q?.focus==='lowercase'?`STAGE ${q.stage} · ${LOWERCASE_STAGES[q.stage-1]}`:'COMPLETE THE TRANSMISSION'}</small><strong>{q?.focus==='lowercase'?(q.upperCue||'♪'):q.display}</strong></div><div className="space-arena" ref={arena} onPointerDown={beginAim} onPointerMove={moveAim} onPointerUp={e=>endAim(e)} onPointerCancel={e=>endAim(e,true)} onLostPointerCapture={e=>endAim(e,true)}>{choices(q.options)}{shot&&<div key={shot.key} style={{left:shipX+'%'}} className={'laser '+(!shot.ok?'miss':'')}/>}<Ship x={shipX} interactive disabled={!active} onFire={fire}/><div className="horizon"/></div><div className="flight-controls"><button aria-label="Steer left" disabled={!active} onClick={()=>steer(-1)}>←</button><button disabled={!active} onClick={fire}>Fire ↑</button><button aria-label="Steer right" disabled={!active} onClick={()=>steer(1)}>→</button><small>Drag & release to snap · tap the ship to fire</small></div></>;
  if(game.id==='asteroids')return <><div className="word-signal"><small>READ THE SIGNAL</small><strong>{q.printCase==='upper'?q.word.toUpperCase():q.word}</strong></div><div className="space-arena">{choices(q.options,v=><span className="picture">{q.pictures[v]}</span>)}<Ship/></div></>;
  if(game.id==='rhyme')return <><div className="planet-core">{q.word}</div><p>Find its rhyming planet.</p>{choices(q.options)}</>;
  if(game.id==='sort')return <><div className="cargo-crate">{q.word}<small>WORD CARGO</small></div><div className="conveyor"/>{choices(q.options,v=><><small>DOCK</small>–{v}</>)}</>;
  if(game.id==='beats')return <><div className="beat-meter">{session.draft.map((_,i)=><i key={i}>●</i>)}</div><button className="drum-pad" disabled={!active||session.draft.length>=6} onClick={()=>{effect(true);void draft([...session.draft,'beat']);}} aria-label="Tap a syllable">🥁<small>TAP A BEAT</small></button><p>{session.draft.length} beats</p></>;
  if(game.id==='search')return <><div className="radar-signal">Find <b>{q.word}</b></div><div className="search-grid">{q.grid.map((c,i)=><button key={i} aria-label={`Row ${Math.floor(i/6)+1} column ${i%6+1}: ${c}`} disabled={!active} className={(session.draft.includes(String(i))?'selected ':'')+mark(String(i))} onClick={()=>{if(session.draft.includes(String(i)))void draft([]);else if(session.draft.length<q.word.length)void draft([...session.draft,String(i)]);}}>{c}</button>)}</div><div className="radar-line"/></>;
  if(game.id==='wordoku')return <><p className="quiet">Letter logic · arcade points, not reading mastery</p><div className="wordoku-grid">{session.draft.map((c,i)=><button key={i} disabled={!active||!!q.grid[i]} className={(q.grid[i]?'given ':'')+(cursor===i?'selected':'')} onClick={()=>setCursor(i)}>{session.help&&!c?q.model[i]:c||'·'}</button>)}</div><div className="tile-bank">{q.tiles.map(t=><button key={t} disabled={!active} onClick={()=>tile(t)}>{q.printCase==='upper'?t.toUpperCase():t}</button>)}</div></>;
  return <>{game.id==='cipher'&&<><div className="cipher-key">{Object.entries(q.key).map(([symbol,c])=><span key={symbol}>{symbol} = {c}</span>)}</div><div className="encoded">{q.code.join(' ')}</div><p className="quiet">Code puzzle · not a test of unaided reading</p></>}{game.id==='transform'&&<div className="transform-signal">{q.from}<span>→</span><b>{session.help?q.word:'?'}</b></div>}{game.id==='builder'&&<div className={"launch-bay dynamic-launch "+(session.phase==="result"?"launched":"")}><img src="/assets/ship-dynamic-v1.png" alt="Your launch ship"/><div className="launch-fuel">{[...q.word].map((_,i)=><i key={i} className={session.draft[i]?"charged":""}/>)}</div><span>BUILD THE LAUNCH WORD · {q.level===1?'72 SHORT WORDS':q.level===2?'FOUR-LETTER WORDS':'LONGER WORDS'}</span></div>}{game.id==='train'&&<div className="railway">🚂<span>THE SENTENCE EXPRESS</span></div>}
   {session.help&&<div className="model">{q.printCase==='upper'?q.word.toUpperCase():q.word}</div>}<div className={'draft-slots '+(game.id==='train'?'carriages':'')}>{Array.from({length:game.id==='train'?q.tiles.length:q.word.length},(_,i)=><button key={i} aria-label={game.id==='builder'?(session.draft[i]?`Remove letter ${session.draft[i].toUpperCase()} at position ${i+1}`:`Empty letter position ${i+1}`):undefined} disabled={game.id==='builder'?session.phase!=='question'||paused||tutorial||!!countdown||!session.draft[i]:!active||game.id!=='transform'} onClick={()=>game.id==='builder'?editBuilder('remove',i):setCursor(i)} className={game.id==='transform'&&cursor===i?'selected':''}>{q.printCase==='upper'?(session.draft[i]||'·').toUpperCase():session.draft[i]||'·'}</button>)}</div>
   {game.id==='builder'&&<div className="builder-edit-controls"><button onClick={()=>editBuilder('backspace')} disabled={session.phase!=='question'||paused||tutorial||!!countdown||!session.draft.length}>⌫ Delete letter</button><button onClick={()=>editBuilder('clear')} disabled={session.phase!=='question'||paused||tutorial||!!countdown}>↶ Start over</button><small>Tap a placed letter to remove it.</small></div>}
   <div className="tile-bank">{q.tiles.map((t,i)=><button key={i} disabled={!active||(game.id==='train'&&session.draft.filter(x=>x===t).length>=q.tiles.filter(x=>x===t).length)} onClick={()=>tile(t)}>{q.printCase==='upper'?t.toUpperCase():t}</button>)}</div></>;
 }
 if(!p)return <main className="loading"><div className="nova-orb"/><h1>Word Arcade</h1><p>{message||'Preparing your starship…'}</p>{message&&<button onClick={()=>load(id)}>Try again</button>}<button className="app-refresh" aria-label="Refresh game" onClick={refreshGame}>↻ Refresh</button></main>;
 return <div className={'arcade-shell arcade-v2 '+(screen==='game'?'is-playing':'')} onPointerDownCapture={()=>void audio.current?.unlock()} onKeyDownCapture={()=>void audio.current?.unlock()}><aside className="tutor-panel"><div className="player-bar"><button aria-label="Pause game" onClick={()=>{stop();setPaused(!paused);void event('pause','toggle');}}>Ⅱ</button><select aria-label="Player" value={id} disabled={busy} onChange={e=>{const next=e.target.value;history.replaceState(null,'',`?player=${next}`);setScreen('gallery');void load(next);}}><option value="explorer">Explorer</option><option value="beginner">Beginner</option><option value="admin">Admin · Admin</option></select></div><div className="coach"><div className={'nova-orb '+(speaking?'speaking':'')}><span>✦</span></div><div className="eyebrow">NOVA · MISSION CONTROL</div><p>{screen==='gallery'?'A universe of words. Where shall we fly today?':screen==='brief'?selected.description:session?.phase==='complete'?LINES[6]:game?.id==='pixel'?INSTRUCTIONS.pixel:displayInstruction(q)}</p><button className="listen" onClick={()=>say(screen==='gallery'?LINES[0]:screen==='brief'?LINES[0]:q?.prompt||INSTRUCTIONS.pixel,true)}>🔊 Hear again</button>{screen!=='gallery'&&<button onClick={home}>← Arcade</button>}</div><div className="sidebar-bottom"><span className="xp">✦ {p.xp} reading XP</span>{id==='admin'&&<strong>ADMIN · SEPARATE TEST SAVE</strong>}<button aria-pressed={sound} onClick={()=>{soundRef.current=!sound;setSound(!sound);if(!needsWordClue(q))stop();void event('voice','coach_chat',String(!sound));}}>{sound?'Coach chat on':'Coach chat off'}</button><small>Saved on this server<br/>No ads. No strangers. Just play.</small></div></aside>
 <div className="active-player-banner" data-player={id} aria-label="Active player">{id==='admin'?'Admin · Admin':p.name}</div>
 <main className={'main-panel '+(screen==='game'?'playing':'')}>
 <div className="audio-toolbar"><button className="app-refresh" aria-label="Refresh game" onClick={refreshGame}>↻ Refresh</button><details className="audio-menu" onKeyDown={e=>{if(e.key==='Escape'){e.currentTarget.open=false;e.currentTarget.querySelector('summary').focus();}}}><summary aria-label="Music and sound settings">♫ <span>{audioPrefs.track==='off'?'Music off':TRACKS.find(t=>t.id===audioPrefs.track)?.name}</span></summary><div className="audio-popover"><fieldset><legend>Background music</legend>{TRACKS.map(t=><label key={t.id}><input type="radio" name="background-music" value={t.id} checked={audioPrefs.track===t.id} onChange={()=>changeAudio({track:t.id})}/>{t.name}</label>)}</fieldset><label className="music-volume">Music volume<input aria-label="Music volume" type="range" min="0" max="100" value={Math.round(audioPrefs.volume*100)} onChange={e=>changeAudio({volume:Number(e.target.value)/100})}/></label><button aria-pressed={audioPrefs.effects} onClick={()=>changeAudio({effects:!audioPrefs.effects})}>Laser & effects: {audioPrefs.effects?'On':'Off'}</button><label className="music-volume">Laser sound<select aria-label="Laser sound" value={audioPrefs.laser} onChange={e=>changeAudio({laser:e.target.value})}>{LASERS.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label><label className="music-volume">Effects volume<input aria-label="Effects volume" type="range" min="0" max="100" value={Math.round(audioPrefs.effectsVolume*100)} onChange={e=>changeAudio({effectsVolume:Number(e.target.value)/100})}/></label><button disabled={!audioPrefs.effects||paused||tutorial} onClick={async()=>{const engine=audio.current;if(await engine?.unlock()){await engine.preloadLaser();engine.laser();}}}>Test laser</button><p>Music softens while Nova speaks.</p><p className="audio-credits">Music: original generated loops<br/>Lasers: Kenney · CC0<br/><a href="/audio/CREDITS.md" target="_blank" rel="noreferrer">Audio sources & credits</a></p>{audioNotice&&<button className="audio-retry" onClick={()=>void audio.current?.unlock()}>{audioNotice}</button>}</div></details></div>
 {screen==='game'&&<div className="compact-controls"><button onClick={home} disabled={busy}>← Arcade</button><button aria-label="Repeat mission instruction" onClick={()=>say(q?.prompt||INSTRUCTIONS.pixel,true)}>🔊</button></div>}
 {screen==='gallery'&&<Lobby p={p} games={GAMES} filter={filter} setFilter={setFilter} choose={choose} resume={()=>{setScreen('game');setPaused(false);setCountdown(0);started.current=Date.now();announce(current.current,true);}}/>}
 {screen==='brief'&&<Brief game={selected} level={level} setLevel={setLevel} mode={mode} setMode={setMode} deck={deck} setDeck={setDeck} focus={practiceFocus} setFocus={setPracticeFocus} busy={busy} onLaunch={launch}/>}
 {screen==='game'&&game&&<><header className="game-header"><div><span className="eyebrow">{game.category}</span><h1>{game.name}</h1></div><div className="game-score">{game.id==='pixel'?'YOUR STUDIO':<><b>{session.score}</b> points <span>Round {Math.min(8,session.round+1)} / 8 · Level {q?.level}</span></>}</div></header>{session.phase==='complete'?<section className="complete"><span className="medal">✦</span><h2>Stellar flying, {p.name}.</h2><strong>{session.score} points</strong>{game.id==='flashcards'&&session.mode==='arcade'&&<p className="race-verdict">{session.correct-session.assisted<6?'Practice finish · try six cards without help next time':(session.activeMs||0)<=120000?'🏆 You beat Comet!':'Finish line reached! Race Comet again?'}</p>}<p>{session.correct-session.assisted} unaided · {session.assisted} with help</p><p>{q?.foundation?'Keep exploring short words. Your next flight has a fresh mix.':q?.focus==='lowercase'?`Lowercase stage ${lowerState(p).stage}: ${LOWERCASE_STAGES[lowerState(p).stage-1]}`:`Next flight starts at level ${session.level}.`}</p><button className="primary" onClick={()=>{setSelected(game);setLevel(session.level);setScreen('brief');}}>Fly again →</button><button onClick={home}>Choose another game</button></section>:<><div className={'game-stage '+(flying(game.id)?'blaster':game.id)+(paused||tutorial||countdown?' frozen':'')}>{puzzle()}</div>{helped&&game.id!=='pixel'&&<div className="help-note" role="status">{session.misses>0&&session.phase==="question"?"Not quite. Try again — no lives lost.":"Teamwork round · help is recorded, not counted as unaided."}</div>}{session.phase==='result'?<div className="result-panel" role="status"><span>✦ +{session.results.at(-1)?.points} · {session.results.at(-1)?.independent?'You did it!':'Made it together!'}</span><button className="primary" onClick={()=>action({kind:'next'})} disabled={busy}>{session.round===7?'Finish flight →':'Next mission →'}</button></div>:game.id!=='pixel'&&<div className="game-controls">{!['lowercase','blaster','asteroids','rhyme','sort','orbit','flashcards','builder'].includes(game.id)&&<><button onClick={()=>draft(game.id==='wordoku'?[...q.grid]:game.id==='transform'?[...q.from]:[])} disabled={!active}>↶ Start over</button><button className="primary" onClick={()=>answer('')} disabled={!active}>Check & launch →</button></>}<button onClick={()=>action({kind:'help'})} disabled={!active}>✦ Show me</button><button onClick={()=>{stop();setTutorial(true);}}>How to play</button></div>}</> }</>}
 {screen==='game'&&countdown>0&&<div className="countdown-overlay" aria-live="polite"><strong key={countdown}>{countdown}</strong><span>Get ready</span></div>}
 {message&&<div className="notice" role="status">{message===q?.prompt?displayInstruction(q):message}</div>}
 <footer>Original games · learning through play · Word Arcade</footer></main>
 {(paused||tutorial)&&<div className="overlay"><section role="dialog" aria-modal="true" aria-label={paused?'Game paused':'How to play'}><div className="nova-orb"><span>✦</span></div><h2>{paused?'Take your time.':'Mission briefing'}</h2><p>{paused?'Your progress is saved. The universe can wait.':game?.description}</p>{tutorial&&<p>{flying(game?.id)?'Listen to the word. Look at the gap. Drag the ship near a letter and release to snap into place. Tap the ship to fire, or tap a letter directly. Wrong shots cost no lives.':q?.prompt||INSTRUCTIONS.pixel}</p>}<button className="primary" onClick={()=>{setPaused(false);setTutorial(false);if(current.current?.session?.phase==='question')announce(current.current,true);}}>Continue →</button><button onClick={()=>{setTutorial(false);home();}}>Back to Arcade</button></section></div>}</div>;
}
