'use client';
import {useEffect,useRef,useState} from 'react';
import {flightWorld,stepFlight,nearestFlyingTarget,launchShot,clamp,dragFlightAim,snapFlightAim,FLIGHT_RECOVERY_MS} from '../lib/flight.mjs';
export default function Flight({q,active,paused,mode='practice',helped,onAnswer,onShot,onEvent,onHear}){
 const ref=useRef(null),world=useRef(null),latest=useRef({}),drag=useRef(null),waiting=useRef(false),coolUntil=useRef(0),alive=useRef(true);
 const [snapshot,setSnapshot]=useState(null),[impact,setImpact]=useState(null),[cooling,setCooling]=useState(false);
 latest.current={active,paused,onAnswer,onShot,onEvent};
 useEffect(()=>{cancelDrag('question');const x=world.current?.ship??50;world.current=flightWorld(q.options,{level:q.level,mode});world.current.ship=x;waiting.current=false;coolUntil.current=0;setCooling(false);setImpact(null);setSnapshot(structuredClone(world.current));},[q.id,mode]);
 useEffect(()=>{alive.current=true;let raf,last=0,paint=0;function frame(now){const w=world.current;if(w){const dt=last?(now-last)/1000:0;last=now;const l=latest.current;
  if(coolUntil.current&&now>=coolUntil.current){coolUntil.current=0;setCooling(false);setImpact(null);}
  const result=stepFlight(w,dt,{paused:l.paused||!l.active||waiting.current||now<coolUntil.current});
  if(result.escaped.length)l.onEvent?.('targets_recycled',String(result.escaped.length));
  if(result.hit){waiting.current=true;setImpact(result.hit);Promise.resolve(l.onAnswer(result.hit.value)).then(d=>{if(!alive.current||world.current!==w)return;if(d?.result?.ok===false||d?.result?.kind==='repeat-ignored'){coolUntil.current=performance.now()+FLIGHT_RECOVERY_MS;setCooling(true);}}).catch(()=>{}).finally(()=>{if(alive.current&&world.current===w)waiting.current=false;});}
  if(now-paint>30){setSnapshot(structuredClone(w));paint=now;}}raf=requestAnimationFrame(frame);}raf=requestAnimationFrame(frame);return()=>{alive.current=false;cancelAnimationFrame(raf);cancelDrag('unmount');};},[]);
 function shoot(id){if(!latest.current.active||latest.current.paused||waiting.current||performance.now()<coolUntil.current)return;const w=world.current;const t=id===undefined?nearestFlyingTarget(w,w.ship):w.targets.find(t=>t.id===id);if(t&&launchShot(w,t.id)){latest.current.onShot();latest.current.onEvent?.('fire',t.value);setSnapshot(structuredClone(w));}}
 function steer(delta){if(!latest.current.active)return;world.current.ship=clamp(world.current.ship+delta,0,100);setSnapshot(structuredClone(world.current));}
 useEffect(()=>{const handler=e=>{if(e.target.closest('input,select,textarea,summary,details')||!latest.current.active)return;if(['ArrowLeft','ArrowRight',' '].includes(e.key)){e.preventDefault();e.key===' '?shoot():steer(e.key==='ArrowLeft'?-8:8);}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);},[]);
 function cancelDrag(reason){const g=drag.current;if(!g)return;drag.current=null;latest.current.onEvent?.('aim_cancel',JSON.stringify({reason,pointer:g.id,type:g.type,x:world.current?.ship}));if(g.owner.hasPointerCapture(g.id))g.owner.releasePointerCapture(g.id);}
 useEffect(()=>{if(!active||paused)cancelDrag('inactive');},[active,paused]);
 useEffect(()=>{const changed=()=>cancelDrag('layout'),blur=()=>cancelDrag('blur'),hidden=()=>{if(document.hidden)cancelDrag('hidden');};const observer=new ResizeObserver(changed);observer.observe(ref.current);window.addEventListener('resize',changed);window.addEventListener('blur',blur);document.addEventListener('visibilitychange',hidden);return()=>{observer.disconnect();window.removeEventListener('resize',changed);window.removeEventListener('blur',blur);document.removeEventListener('visibilitychange',hidden);};},[]);
 function begin(e){if(!active||paused||e.button!==0||e.isPrimary===false||drag.current||e.target.closest('.flying-target'))return;const b=ref.current.getBoundingClientRect(),ship=!!e.target.closest('.pilot');drag.current={id:e.pointerId,type:e.pointerType,start:e.clientX,startY:e.clientY,lastX:e.clientX,ship,moved:false,width:b.width,left:b.left,owner:e.currentTarget,from:world.current.ship,min:world.current.ship,max:world.current.ship};e.currentTarget.setPointerCapture(e.pointerId);latest.current.onEvent?.('aim_begin',JSON.stringify({pointer:e.pointerId,type:e.pointerType,x:world.current.ship,clientX:e.clientX,width:b.width,ship}));e.preventDefault();}
 function move(e){const g=drag.current;if(g?.id!==e.pointerId||!active||paused)return;const b=ref.current.getBoundingClientRect();if(Math.abs(b.width-g.width)>1||Math.abs(b.left-g.left)>1){cancelDrag('layout');return;}g.moved ||= Math.hypot(e.clientX-g.start,e.clientY-g.startY)>8;if(g.moved){world.current.ship=dragFlightAim(world.current.ship,e.clientX-g.lastX,g.width);g.lastX=e.clientX;g.min=Math.min(g.min,world.current.ship);g.max=Math.max(g.max,world.current.ship);}}
 function end(e,canceled=false){const g=drag.current;if(g?.id!==e.pointerId)return;if(canceled){cancelDrag('pointer');return;}move(e);if(drag.current!==g)return;drag.current=null;if(active&&!paused){if(g.moved)world.current.ship=snapFlightAim(world.current,world.current.ship);latest.current.onEvent?.('aim_release',JSON.stringify({x:world.current.ship,from:g.from,min:g.min,max:g.max,moved:g.moved,pointer:g.id,type:g.type,clientX:e.clientX}));setSnapshot(structuredClone(world.current));}if(g.owner.hasPointerCapture(g.id))g.owner.releasePointerCapture(g.id);if(active&&!paused&&g.ship&&!g.moved)shoot();}
 const lower=q.focus==='lowercase';
 return <div className="flight-game"><div className="mission-target"><small>{q.game==='rhyme'?'FIND THE RHYME':q.game==='asteroids'?'READ IT · FIND ITS PICTURE':lower?'FIND ITS LITTLE PARTNER':'BLAST THE MISSING LETTER'}</small><strong>{lower?q.upperCue||'♪':q.display||q.word?.toUpperCase()}</strong></div>
 {q.game==='rhyme'&&<div className="rhyme-listen" aria-label="Hear the word choices"><small>Hear choices:</small>{q.options.map(word=><button key={word} disabled={!active} aria-label={`Hear ${word}`} onClick={()=>onHear?.(word)}>🔊 {word.toUpperCase()}</button>)}</div>}
 <div className="flight-world" aria-label="Moving targets. Drag to steer, tap ship or press Space to shoot." onPointerDown={begin} onPointerMove={move} onPointerUp={e=>end(e)} onPointerCancel={e=>end(e,true)} onLostPointerCapture={e=>end(e,true)}>
 <div className="flight-lanes" ref={ref}>
 <div className="flight-stars"/>{snapshot?.targets.map(t=><button key={t.id} disabled={!active||!!snapshot.shots.length} className={'flying-target '+(helped&&t.value===q.answer?'hint-glow':'')} style={{left:t.x+'%',top:t.y+'%'}} onClick={()=>shoot(t.id)} aria-label={q.pictures?`Picture ${t.value}`:t.value}>{q.pictures?q.pictures[t.value]:q.printCase==='upper'||q.game==='rhyme'?t.value.toUpperCase():t.value}</button>)}
 {snapshot?.shots.map(s=><i className="projectile" key={s.id} style={{left:s.x+'%',top:s.y+'%'}}/>)}
 {impact&&<div className="impact-ring" style={{left:impact.x+'%',top:impact.y+'%'}}><span>✦</span></div>}
 <button className="pilot" disabled={!active} aria-label="Fire spaceship" style={{left:(snapshot?.ship??50)+'%'}} onClick={e=>{if(e.detail===0)shoot();}}><img src="/assets/ship-dynamic-v1.png" alt="" draggable="false"/></button><div className="flight-baseline"/>
</div></div><div className="arcade-inputs"><button disabled={!active} onClick={()=>steer(-12)} aria-label="Steer left">←</button><button className="fire-button" disabled={!active||cooling||!!snapshot?.shots.length} onClick={()=>shoot()}>{cooling?'AIM AGAIN':snapshot?.shots.length?'FIRING…':'FIRE'}</button><button disabled={!active} onClick={()=>steer(12)} aria-label="Steer right">→</button><small>{cooling?'Try a different target.':mode==='practice'?'Targets come around again. Take your time.':'Fast flight · aim, snap, blast!'} </small></div></div>;
}
