'use client';
import {useEffect,useRef,useState} from 'react';
import {flightWorld,stepFlight,nearestFlyingTarget,launchShot,clamp,flightAim,snapFlightAim} from '../lib/flight.mjs';
export default function Flight({q,active,paused,mode='practice',helped,onAnswer,onShot,onEvent,onHear}){
 const ref=useRef(null),world=useRef(null),latest=useRef({}),drag=useRef(null),waiting=useRef(false);
 const [snapshot,setSnapshot]=useState(null),[impact,setImpact]=useState(null);
 latest.current={active,paused,onAnswer,onShot,onEvent};
 useEffect(()=>{world.current=flightWorld(q.options,{level:q.level,mode});waiting.current=false;setImpact(null);setSnapshot(structuredClone(world.current));},[q.id,mode]);
 useEffect(()=>{let raf,last=0,paint=0;function frame(now){const w=world.current;if(w){const dt=last?(now-last)/1000:0;last=now;const l=latest.current;const result=stepFlight(w,dt,{paused:l.paused||!l.active||waiting.current});if(result.escaped.length)l.onEvent?.('targets_recycled',String(result.escaped.length));if(result.hit){waiting.current=true;setImpact(result.hit);Promise.resolve(l.onAnswer(result.hit.value)).finally(()=>{waiting.current=false;setTimeout(()=>setImpact(null),500)});}if(now-paint>30){setSnapshot(structuredClone(w));paint=now;}}raf=requestAnimationFrame(frame);}raf=requestAnimationFrame(frame);return()=>cancelAnimationFrame(raf);},[]);
 function shoot(id){if(!latest.current.active||waiting.current)return;const w=world.current;const t=id===undefined?nearestFlyingTarget(w,w.ship):w.targets.find(t=>t.id===id);if(t&&launchShot(w,t.id)){latest.current.onShot();latest.current.onEvent?.('fire',t.value);setSnapshot(structuredClone(w));}}
 function steer(delta){if(!latest.current.active)return;world.current.ship=clamp(world.current.ship+delta,0,100);setSnapshot(structuredClone(world.current));}
 useEffect(()=>{const handler=e=>{if(e.target.closest('input,select,textarea,summary,details')||!latest.current.active)return;if(['ArrowLeft','ArrowRight',' '].includes(e.key)){e.preventDefault();e.key===' '?shoot():steer(e.key==='ArrowLeft'?-8:8);}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);},[]);
 function point(e,offset=0){const b=ref.current.getBoundingClientRect();return flightAim(e.clientX,b.left,b.width,offset);}
 function begin(e){if(!active||e.button!==0||e.isPrimary===false||drag.current||e.target.closest('.flying-target'))return;const b=ref.current.getBoundingClientRect(),ship=!!e.target.closest('.pilot');drag.current={id:e.pointerId,start:e.clientX,startY:e.clientY,ship,moved:false,offset:ship?e.clientX-(b.left+world.current.ship*b.width/100):0};e.currentTarget.setPointerCapture(e.pointerId);if(!ship)world.current.ship=point(e);e.preventDefault();}
 function move(e){const g=drag.current;if(g?.id!==e.pointerId||!active)return;g.moved ||= Math.hypot(e.clientX-g.start,e.clientY-g.startY)>8;if(g.moved)world.current.ship=point(e,g.offset);}
 function end(e,canceled=false){const g=drag.current;if(g?.id!==e.pointerId)return;drag.current=null;g.moved ||= Math.hypot(e.clientX-g.start,e.clientY-g.startY)>8;if(!canceled&&active){if(g.moved)world.current.ship=point(e,g.offset);world.current.ship=snapFlightAim(world.current,world.current.ship);latest.current.onEvent?.('aim_release',JSON.stringify({x:world.current.ship,moved:g.moved}));setSnapshot(structuredClone(world.current));}if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);if(!canceled&&g.ship&&!g.moved)shoot();}
 const lower=q.focus==='lowercase';
 return <div className="flight-game"><div className="mission-target"><small>{q.game==='rhyme'?'FIND THE RHYME':q.game==='asteroids'?'READ IT · FIND ITS PICTURE':lower?'FIND ITS LITTLE PARTNER':'BLAST THE MISSING LETTER'}</small><strong>{lower?q.upperCue||'♪':q.display||q.word?.toUpperCase()}</strong></div>
 {q.game==='rhyme'&&<div className="rhyme-listen" aria-label="Hear the word choices"><small>Hear choices:</small>{q.options.map(word=><button key={word} disabled={!active} aria-label={`Hear ${word}`} onClick={()=>onHear?.(word)}>🔊 {word.toUpperCase()}</button>)}</div>}
 <div className="flight-world" aria-label="Moving targets. Drag to steer, tap ship or press Space to shoot." onPointerDown={begin} onPointerMove={move} onPointerUp={e=>end(e)} onPointerCancel={e=>end(e,true)} onLostPointerCapture={e=>end(e,true)}>
 <div className="flight-lanes" ref={ref}>
 <div className="flight-stars"/>{snapshot?.targets.map(t=><button key={t.id} disabled={!active||!!snapshot.shots.length} className={'flying-target '+(helped&&t.value===q.answer?'hint-glow':'')} style={{left:t.x+'%',top:t.y+'%'}} onClick={()=>shoot(t.id)} aria-label={q.pictures?`Picture ${t.value}`:t.value}>{q.pictures?q.pictures[t.value]:q.printCase==='upper'||q.game==='rhyme'?t.value.toUpperCase():t.value}</button>)}
 {snapshot?.shots.map(s=><i className="projectile" key={s.id} style={{left:s.x+'%',top:s.y+'%'}}/>)}
 {impact&&<div className="impact-ring" style={{left:impact.x+'%',top:impact.y+'%'}}><span>✦</span></div>}
 <button className="pilot" disabled={!active} aria-label="Fire spaceship" style={{left:(snapshot?.ship??50)+'%'}} onClick={e=>{if(e.detail===0)shoot();}}><img src="/assets/ship-dynamic-v1.png" alt="" draggable="false"/></button><div className="flight-baseline"/>
 </div></div><div className="arcade-inputs"><button disabled={!active} onClick={()=>steer(-12)} aria-label="Steer left">←</button><button className="fire-button" disabled={!active||!!snapshot?.shots.length} onClick={()=>shoot()}>{snapshot?.shots.length?'FIRING…':'FIRE'}</button><button disabled={!active} onClick={()=>steer(12)} aria-label="Steer right">→</button><small>{mode==='practice'?'Targets come around again. Take your time.':'Fast flight · aim, snap, blast!'} </small></div></div>;
}
