'use client';
import {GAME_IDENTITIES} from '../lib/game-identities.mjs';
function GameCover({game}){const identity=GAME_IDENTITIES[game.id];return <div className="live-cover distinct-cover" role="img" aria-label={identity.label}><span className="identity-icon" aria-hidden="true">{identity.icon}</span><span className="identity-example" aria-hidden="true">{identity.example}</span></div>;}
export const PLAY_GAMES=['blaster','orbit','rhyme','sort','asteroids','builder'];
const titles={blaster:'Aim. Blast. Spell.',orbit:'Connect a flight path.',rhyme:'Hunt a moving rhyme.',sort:'Drag. Group. Dock.',asteroids:'Read it. Rescue it.',builder:'Build it. Launch it.'};
export function Lobby({p,games,filter,setFilter,choose,resume}){
 const section=filter==='foundation'?'arcade':filter;
 return <section className="lobby"><header className="lobby-header"><img src="/icons/app-192-v1.png" width="58" height="58" alt="Word Arcade"/><div><span>MISSION SELECT</span><h1>Word Arcade</h1></div><span className="lobby-xp">✦ {p.xp} XP</span></header><nav className="lobby-tabs" aria-label="Activities">{[['arcade','🚀 Arcade'],['flashcards','⚑ Flashcards'],['puzzles','▦ Puzzle lab'],['all','All games']].map(([value,label])=><button key={value} className={section===value?'chosen-tab':''} onClick={()=>setFilter(value)}>{label}</button>)}</nav>
 {p.session&&<button className="resume-strip" onClick={resume}>▶ Continue {games.find(g=>g.id===p.session.game)?.name} <span>{p.session.phase==='complete'?'See your result':`${Math.min(8,p.session.round+1)} / 8`}</span></button>}
 {section==='flashcards'?<><h2>Pick a deck. Set your pace.</h2><div className="deck-grid">{[['letters','Big to little','A → a','Match uppercase and lowercase.'],['words','Missing letters','C _ T','Hear a short word. Find the gap.'],['spelling','Listen & spell','♪ → CAT','Build a word from memory.']].map(([deck,name,example,description])=><button className="deck-card" key={deck} onClick={()=>choose(games.find(g=>g.id==='flashcards'),deck)}><div className={"deck-picture deck-"+deck}><span aria-hidden="true">{deck==='letters'?'🔠':deck==='words'?'🧩':'🎧'}</span>{example}</div><h3>{name}</h3><p>{description}</p><span>Practice or race →</span></button>)}</div></>:<><h2>{section==='puzzles'?'Slow down. Work it out.':'Choose your flight.'}</h2><div className="live-game-grid">{games.filter(g=>section==='all'||(section==='arcade'?PLAY_GAMES.includes(g.id):!PLAY_GAMES.includes(g.id)&&g.id!=='flashcards')).map(g=><button className={'live-game-card game-'+g.id} key={g.id} style={{'--accent':g.color}} onClick={()=>choose(g)}><GameCover game={g}/><div className="live-card-copy"><small>{g.category}</small><h3>{g.name}</h3><p>{titles[g.id]||g.description}</p><span>{p.games[g.id]?.played?'↻ Play again':'▶ Play'}</span>{p.games[g.id]?.best>0&&<em>Best {p.games[g.id].best}</em>}</div></button>)}</div></>}
 </section>;
}
export function Brief({game,level,setLevel,mode,setMode,deck,setDeck,focus,setFocus,busy,onLaunch}){
 return <section className="mission-brief"><span className="brief-identity" role="img" aria-label={GAME_IDENTITIES[game.id].label}>{GAME_IDENTITIES[game.id].icon}</span><span className="eyebrow">READY TO PLAY?</span><h1>{game.name}</h1><p>{game.description}</p>{['blaster','asteroids','rhyme','orbit','sort','flashcards'].includes(game.id)&&<div className="pace-picker" role="group" aria-label="Game pace"><button className={mode==='practice'?'chosen-tab':''} onClick={()=>setMode('practice')}><strong>Practice</strong><small>Room to think. No rush.</small></button><button className={mode==='arcade'?'chosen-tab':''} onClick={()=>setMode('arcade')}><strong>{game.id==='flashcards'?'Race Comet':'Arcade'}</strong><small>{game.id==='flashcards'?'Beat the pace ship.':'Faster flight. Same words.'}</small></button></div>}{game.id==='flashcards'&&<div className="deck-picker">{[['letters','A → a'],['words','C _ T'],['spelling','Listen & spell']].map(([v,t])=><button key={v} className={deck===v?'chosen-tab':''} onClick={()=>setDeck(v)}>{t}</button>)}</div>}{game.id==='blaster'&&<div className="deck-picker"><button className={focus==='words'?'chosen-tab':''} onClick={()=>setFocus('words')}>Short words · ABC</button><button className={focus==='lowercase'?'chosen-tab':''} onClick={()=>setFocus('lowercase')}>Little letters · abc</button></div>}{!['pixel','blaster','builder','asteroids','orbit','flashcards'].includes(game.id)&&<div className="deck-picker">{[1,2,3].map(n=><button key={n} className={level===n?'chosen-tab':''} onClick={()=>setLevel(n)}>Level {n}</button>)}</div>}<button className="primary launch-button" onClick={onLaunch} disabled={busy}>Let’s play →</button><small className="quiet">New flights replace unfinished rounds. Your earned XP stays.</small></section>;
}
